<?php 
use rdks\core\framework\Login;
use rdks\core\framework\Language; 
use rdks\core\page\Template; 
?>
	<div class="row">
		<div class="col-md-6">

			<div class="well">
				<h3><?php echo TEXT_USERS; ?></h3>
				<?php if(isset($data['users']) || isset($access['all']) || Login::isSuperAdmin() || Login::roleSuperAdmin()): ?>
				<ul class="list-group">
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input type="checkbox" rel="rdks-form-check-all" data-input=".checkbox-users" class="checkbox-permissions"> <b><?php echo TEXT_ALL; ?></b> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['descendants'])) );?> type="checkbox" name="data[users][descendants]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_MANAGE_DESCENDANTS; ?> 

						      <span id="help-users" data-text="<?php echo TEXT_MANAGE_DESCENDANTS_DESC; ?>"  class="help"></span>
						   
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['tree'])) );?> type="checkbox" name="data[users][tree]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_MANAGE_TREE_DESCENDANTS; ?> 

						      <span id="help-users-alt" data-text="<?php echo TEXT_MANAGE_TREE_DESCENDANTS_DESC; ?>"  class="help"></span>
						   
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['password'])) );?> type="checkbox" name="data[users][password]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_CHANGE_PASSWORD; ?>  
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['reset'])) );?> type="checkbox" name="data[users][reset]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_RESET_PASSWORD; ?>  
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['view'])) );?> type="checkbox" name="data[users][view]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_VIEW; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['create'])) );?> type="checkbox" name="data[users][create]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_CREATE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['edit'])) );?> type="checkbox" name="data[users][edit]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_EDIT; ?> 
						    </label>
						</div>	
					</li>			
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['visibility'])) );?> type="checkbox" name="data[users][visibility]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_ENABLE_DISABLE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['trash'])) );?> type="checkbox" name="data[users][trash]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_TRASH; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['expiration'])) );?> type="checkbox" name="data[users][expiration]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_EXPIRATION_DATE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['picture'])) );?> type="checkbox" name="data[users][picture]" value="1" class="checkbox-users checkbox-permissions"> <?php echo TEXT_PROFILE_PICTURE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['logs'])) );?> type="checkbox" name="data[users][logs]" value="1" class="checkbox-users checkbox-permissions"> Logs 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['users']['logout'])) );?> type="checkbox" name="data[users][logout]" value="1" class="checkbox-users checkbox-permissions"> <?php echo Language::translate("Force to log out","Forzar salida"); ?> 
						    </label>
						</div>	
					</li>										
				</ul>
				<?php else: ?>
					<div class="alert alert-info" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span class="alert-text"><?php echo TEXT_UNAVAILABLE_ROLE; ?></span>
					</div>
				<?php endif; ?>	
			</div><!-- .well -->

		</div><!-- .col-md-6 -->

		<div class="col-md-6">

			<div class="well">
				<h3><?php echo TEXT_SUBSCRIBERS; ?></h3>
				<?php if(isset($data['subscribers']) || isset($access['all']) || Login::isSuperAdmin() || Login::roleSuperAdmin()): ?>
				<ul class="list-group">
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input type="checkbox" rel="rdks-form-check-all" data-input=".checkbox-subscribers" class="checkbox-permissions"> <b><?php echo TEXT_ALL; ?></b> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['descendants'])) );?> type="checkbox" name="data[subscribers][descendants]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_MANAGE_DESCENDANTS; ?> 

						      <span id="help-subscribers" data-text="<?php echo TEXT_MANAGE_DESCENDANTS_DESC; ?>"  class="help"></span>
						   
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['tree'])) );?> type="checkbox" name="data[subscribers][tree]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_MANAGE_TREE_DESCENDANTS; ?> 

						      <span id="help-subcribers-alt" data-text="<?php echo TEXT_MANAGE_TREE_DESCENDANTS_DESC; ?>" class="help"></span>
						   
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['password'])) );?> type="checkbox" name="data[subscribers][password]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_CHANGE_PASSWORD; ?>  
						    </label>
						</div>	
					</li>										
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['reset'])) );?> type="checkbox" name="data[subscribers][reset]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_RESET_PASSWORD; ?>  
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['view'])) );?> type="checkbox" name="data[subscribers][view]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_VIEW; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['create'])) );?> type="checkbox" name="data[subscribers][create]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_CREATE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['edit'])) );?> type="checkbox" name="data[subscribers][edit]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_EDIT; ?> 
						    </label>
						</div>	
					</li>			
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['visibility'])) );?> type="checkbox" name="data[subscribers][visibility]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_ENABLE_DISABLE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['trash'])) );?> type="checkbox" name="data[subscribers][trash]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_TRASH; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['expiration'])) );?> type="checkbox" name="data[subscribers][expiration]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_EXPIRATION_DATE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['picture'])) );?> type="checkbox" name="data[subscribers][picture]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo TEXT_PROFILE_PICTURE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['logs'])) );?> type="checkbox" name="data[subscribers][logs]" value="1" class="checkbox-subscribers checkbox-permissions"> Logs 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['subscribers']['logout'])) );?> type="checkbox" name="data[subscribers][logout]" value="1" class="checkbox-subscribers checkbox-permissions"> <?php echo Language::translate("Force to log out","Forzar salida"); ?> 
						    </label>
						</div>	
					</li>	
				</ul>
				<?php else: ?>
					<div class="alert alert-info" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span class="alert-text"><?php echo TEXT_UNAVAILABLE_ROLE; ?></span>
					</div>
				<?php endif; ?>	
			</div><!-- .well -->

		</div><!-- .col-md-6 -->

	</div><!-- .row -->

	<div class="row">

		<div class="col-md-6">

			<div class="well">
				<h3><?php echo TEXT_CLIENTS; ?></h3>
				<?php if(isset($data['clients']) || isset($access['all']) || Login::isSuperAdmin() || Login::roleSuperAdmin()): ?>
				<ul class="list-group">
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input type="checkbox" rel="rdks-form-check-all" data-input=".checkbox-clients" class="checkbox-permissions"> <b><?php echo TEXT_ALL; ?></b> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['descendants'])) );?> type="checkbox" name="data[clients][descendants]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_MANAGE_DESCENDANTS; ?> 

						      <span id="help-clients" data-text="<?php echo TEXT_MANAGE_DESCENDANTS_DESC; ?>"  class="help"></span>
						   
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['tree'])) );?> type="checkbox" name="data[clients][tree]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_MANAGE_TREE_DESCENDANTS; ?> 

						      <span id="help-subcribers-alt" data-text="<?php echo TEXT_MANAGE_TREE_DESCENDANTS_DESC; ?>" class="help"></span>
						   
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['password'])) );?> type="checkbox" name="data[clients][password]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_CHANGE_PASSWORD; ?>  
						    </label>
						</div>	
					</li>					
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['reset'])) );?> type="checkbox" name="data[clients][reset]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_RESET_PASSWORD; ?>  
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['view'])) );?> type="checkbox" name="data[clients][view]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_VIEW; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['create'])) );?> type="checkbox" name="data[clients][create]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_CREATE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['edit'])) );?> type="checkbox" name="data[clients][edit]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_EDIT; ?> 
						    </label>
						</div>	
					</li>			
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['visibility'])) );?> type="checkbox" name="data[clients][visibility]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_ENABLE_DISABLE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['trash'])) );?> type="checkbox" name="data[clients][trash]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_TRASH; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['expiration'])) );?> type="checkbox" name="data[clients][expiration]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_EXPIRATION_DATE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['picture'])) );?> type="checkbox" name="data[clients][picture]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo TEXT_PROFILE_PICTURE; ?> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['logs'])) );?> type="checkbox" name="data[clients][logs]" value="1" class="checkbox-clients checkbox-permissions"> Logs 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['clients']['logout'])) );?> type="checkbox" name="data[clients][logout]" value="1" class="checkbox-clients checkbox-permissions"> <?php echo Language::translate("Force to log out","Forzar salida"); ?> 
						    </label>
						</div>	
					</li>	
				</ul>
				<?php else: ?>
					<div class="alert alert-info" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span class="alert-text"><?php echo TEXT_UNAVAILABLE_ROLE; ?></span>
					</div>
				<?php endif; ?>	
			</div><!-- .well -->

		</div><!-- .col-md-6 -->

		<div class="col-md-6">
			<div class="well">
	
				<h3>Roles</h3>
				<?php if(isset($data['roles']) || isset($access['all']) || Login::isSuperAdmin() || Login::roleSuperAdmin()): ?>
				<ul class="list-group">
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input type="checkbox" rel="rdks-form-check-all" data-input=".checkbox-roles" class="checkbox-permissions"> <b><?php echo TEXT_ALL; ?></b> 
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['roles']['view'])) );?> type="checkbox" name="data[roles][view]" value="1" class="checkbox-roles checkbox-permissions"> <?php echo TEXT_VIEW; ?>  
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['roles']['create'])) );?> type="checkbox" name="data[roles][create]" value="1" class="checkbox-roles checkbox-permissions"> <?php echo TEXT_CREATE; ?>  
						    </label>
						</div>	
					</li>
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['roles']['edit'])) );?> type="checkbox" name="data[roles][edit]" value="1" class="checkbox-roles checkbox-permissions"> <?php echo TEXT_EDIT; ?>  
						    </label>
						</div>	
					</li>			
					<li class="list-group-item">
						<div class="checkbox" style="margin:0;">
						    <label>
						      <input<?php echo Template::checked( (isset($data['roles']['visibility'])) );?> type="checkbox" name="data[roles][visibility]" value="1" class="checkbox-roles checkbox-permissions"> <?php echo TEXT_ENABLE_DISABLE; ?>  
						    </label>
						</div>	
					</li>
				</ul>
				<?php else: ?>
					<div class="alert alert-info" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span class="alert-text"><?php echo TEXT_UNAVAILABLE_ROLE; ?></span>
					</div>
				<?php endif; ?>	
			</div><!-- .well -->
		</div><!-- .col-md-6 -->	
	</div><!-- .row -->