#!/usr/bin/env php
<?php
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

if(!isset($argv) || php_sapi_name() != "cli") die("Unauthorized to access"); 

$params = [];
$values = [];
$p = 0;

if(is_array($argv) && count($argv) > 0):
unset($argv[0]);
    foreach ($argv as $arg): $p++;
    	if(preg_match('#=#', $arg)):
        	list($k, $v) = explode("=",$arg);
       		$values[$k] = $v;
       	else:

       		if($p == 2 && !in_array($arg, ['--dev','--pro'])):
       			$params[] = 'pro';
       			$values['pro'] = 1;

       		else:
       			$x = str_replace('--', '', $arg);
       			
       			$params[] = $x;
       			$values[$x] = 1;

       		endif;

       	endif;
    endforeach;
endif;

/*
|--------------------------------|
|		 LOAD BOOTSTRAP			 |
|--------------------------------|
*/
require "./core/Framework/Bootstrap.php";

use Roducks\Framework\Core;
use Roducks\Framework\CLI;
use Roducks\Framework\Environment;
use Roducks\Framework\Helper;

Core::loadFile(DIR_APP_LANGUAGES, 'en' . FILE_INC);

/*
|--------------------------------|
|		 CHECK ENVIRONMENT  	 |
|--------------------------------|
*/

$db_name = "database";
$dev = isset($values['dev']);
$db = (isset($values['db'])) ? $values['db'] : $db_name;

if ($dev) {
	$db_name = $db.'.local';
}

$environment = [
	'errors' => $dev,
	'subdomain' => "www",
	'site' => "Front",
	'mode' => Environment::CLI,
	'database' => $db_name
];

/*
|--------------------------------|
|			RUN SCRIPT  		 |
|--------------------------------|
*/
require "./core/Framework/Run" . FILE_EXT;

if(isset($params[0])){

	$method = "output";
	$name = $params[0];

	if(preg_match('#:#', $name)){
		list($name, $method) = explode(":", $name);
	}

	$cls = $name;
	$name = Helper::getCamelName($name);
	$script = "App\\CLI\\" . $name;

	if(!class_exists($script)) {
		return;
	}
	
	$class = new $script($values);
	if(method_exists($class, $method)){
		$class->$method();
	} else {
		CLI::println("Unknown command: {$cls}::{$method}", CLI::FAILURE);
	}
	
}else{
	CLI::println("Please set a command", CLI::FAILURE);
}

