<?php 
use rdks\core\page\Block;
use rdks\core\page\Template;
use rdks\core\framework\Login;
use rdks\core\framework\Role;
?>
<div class="text-centered"><h1 style="margin: 0 0 10px 0;"><?php echo TEXT_WELCOME; ?></h1></div>
<div class="text-centered profile-dashboard"><?php Block::load("user", ['type' => Role::TYPE_USERS]); ?></div>
<h3><?php echo Login::getAdminFullName(); ?></h3>
<p><span class="glyphicon glyphicon-star<?php echo Template::conditional(Login::isSuperAdmin(),'','-empty'); ?>" aria-hidden="true"></span> <?php echo Login::getAdminData('role'); ?></p>
<p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <?php echo Login::getAdminEmail(); ?></p>