<?php 
use Roducks\Page\Block;
use Roducks\Page\Template;
use Roducks\Framework\Login;
?>
<div class="text-centered"><h1 style="margin: 0 0 10px 0;"><?php echo TEXT_WELCOME; ?></h1></div>
<div class="text-centered profile-dashboard"><?php Block::load("user", ['session' => Login::SESSION_ADMIN]); ?></div>
<h3><?php echo Login::getAdminFullName(); ?></h3>
<p><span class="glyphicon glyphicon-star<?php echo Template::conditional(Login::isSuperAdmin(),'','-empty'); ?>" aria-hidden="true"></span> <?php echo Login::getAdminData('role'); ?></p>
<p><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <?php echo Login::getAdminEmail(); ?></p>