<?php

use Roducks\Framework\Core;
use Roducks\Framework\Path;
use Roducks\Framework\Environment;
use Roducks\Framework\URL;
use Roducks\Framework\Login;
use Roducks\Framework\Role;
use Roducks\Page\Block;
use Roducks\Page\Template;

?>
<div id="top" style="height:50px;"></div>
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
<div class="container">

<?php if(Login::isAdminLoggedIn()): ?>
	<!-- Brand and toggle get grouped for better mobile display -->
	<div class="navbar-header">
		<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
		<a class="navbar-brand" href="/" style="position:relative; top:-4px;"><img src="<?php echo Path::getImage("rdks_logo_color_mini.png"); ?>" /></a>
	</div>
<?php endif; ?>
	<!-- Collect the nav links, forms, and other content for toggling -->
	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

	<ul class="nav navbar-nav">
		<li><a href="<?php echo URL::getFrontURL(); ?>"><span class="glyphicon glyphicon-home" aria-hidden="true"></span> <span class="sr-only">(current)</span></a></li>
		<?php if(Login::isAdminLoggedIn()): ?>
		<li><a href="/"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span> Dashboard</a></li>
		<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo __('Users'); ?> <span class="caret"></span></a>
			<?php Block::load("menu/access", ['type' => Role::TYPE_USERS, 'items' => Template::menu("top-admin"), 'tpl' => "top"]); ?>
		</li>
		<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?php echo __('Content'); ?> <span class="caret"></span></a>
			<?php Block::load("menu/access", ['type' => Role::TYPE_USERS, 'items' => Template::menu("top-content"), 'tpl' => "top"]); ?>
		</li>
		<?php endif; ?>
	</ul>

	<?php Block::load("language/output/{$_PAGE_ID}/nav"); ?>

	<?php if(Login::isAdminLoggedIn()): ?>
		<ul class="nav navbar-nav navbar-right">
			<li class="dropdown">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
				<?php Block::load("user", ['session' => Login::SESSION_ADMIN, 'size' => 20]); ?> <?php echo Login::getAdminName(); ?> <span class="caret"></span>
			</a>
				<?php Block::load("menu/access", ['type' => Role::TYPE_USERS, 'items' => Template::menu("top-account"), 'tpl' => "top", 'permission' => "users"]); ?>
			</li>
		</ul>
	<?php endif; ?>
	</div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>

<?php if(Environment::inDEV()): ?>
<div class="alert alert-warning" role="alert">
	<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
	<span class="alert-text"><?php echo TEXT_APP_IN_DEV_MODE; ?></span>
</div>
<?php endif; ?>
