<?php use rdks\core\framework\Form; ?>
<div class="container">
	<h1><?php echo TEXT_CONTACT_US; ?></h1>

	<div class="row">
		<div class="col-md-6">

			<form id="foovar" name="foovar" method="post" 
			rel="rdks-form" 
			data-notification="true" 
			data-callback-success="cbFormSuccess" 
			data-callback-loading="cbFormLoading" 
			data-callback-error="cbFormError" 
		    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
		    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
		    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
			data-reset="true" 
			data-ajax="true" 
			data-json="true" 
			data-focus="true" 
			action="<?php echo "/contact-us/submit"; ?>">

			<input type="hidden" name="form-key" value="<?php echo Form::getKey(); ?>" />

			<div class="form-group has-feedback">
				<label class="control-label" for="first_name"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_FIRST_NAME; ?></label>
				<input type="text" name="first_name" class="form-control" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="words" 
				/>
				<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				<span class="help-block"></span>
			</div>

			<div class="form-group has-feedback">
				<label class="control-label" for="last_name"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_LAST_NAME; ?></label>
				<input type="text" name="last_name" class="form-control" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="words" 
				/>
				<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				<span class="help-block"></span>
			</div>	

			<div class="form-group has-feedback">
				<label class="control-label" for="email"><span class="rdks-ui-color-red">*</span> Email</label>
				<input type="text" name="email" class="form-control" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="email" 
				/>
				<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				<span class="help-block"></span>
			</div>				

			<div class="form-group has-feedback">
				<label class="control-label" for="last_name"><span class="rdks-ui-color-red">*</span> Comment</label>
				<textarea name="comment" class="form-control" rows="5" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="words" 
				/></textarea>
				<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				<span class="help-block"></span>
			</div>						

			<button type="submit" class="btn btn-lg btn-info navbar-btn">
				<span class="glyphicon glyphicon-send" aria-hidden="true"></span> <?php echo TEXT_SUBMIT; ?>
			</button>

			</form>

		</div>
	</div>

</div>