<div class="container">
	<br>
	<div class="row">
		<div class="col-xs-6">
			<h1><?php echo TEXT_FORGOTTEN_PASSWORD; ?></h1>

			<form id="foovar" name="foovar" method="post" 
			rel="rdks-form" 
			data-notification="true" 
			data-callback-success="cbFormRedirectSuccess" 
			data-callback-loading="cbFormLoading" 
			data-callback-error="cbFormError" 
		    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
		    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
		    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
			data-reset="true" 
			data-ajax="true" 
			data-json="true" 
			data-focus="true" 
			action="/account/recover-password">

			<div class="form-group has-feedback">
			  <label class="control-label" for="email"><span class="rdks-ui-color-red">*</span> Email</label>
				<input type="text" class="form-control" name="email"
				rel="rdks-form-input-post" 
				data-url="/account/check" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="email" 
				/>
			  <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			  <span class="help-block"></span>
			</div>		

			<button type="submit" class="btn btn-lg btn-info navbar-btn">
				<span class="glyphicon glyphicon-send" aria-hidden="true"></span> <?php echo TEXT_SUBMIT; ?>
			</button>

			</form>

		</div>
	</div>

</div>
