<?php
use Roducks\Framework\UI;
?>
<div class="bg-home">
	<?php echo UI::getImage("roducks_logo_home.png", 372, [
		'flex-w' => true, // width: auto, height: 372px
		'center' => true,
		'bg' => UI::BG_TRANSPARENT, // UI::BG_WHITE | UI::BG_BLACK
		'rel' => "rdks-image-scale",
		'class' => "rdks-image-responsive"
	]); ?>
</div>
<br>
<div class="container">

	<div class="well">

	<span><b>Version:</b> 1.0</span>
	<br><br>
	<p>
		A <b>PHP</b> modern, scalable and light <b>MVC</b> framework that works with a <b>MySQL</b> database that includes its own <b>ORM</b> for <b>SQL</b> transactions and it also has many other features and libraries to make a great and secure Web Application. It's integrited with <b>Bootstrap</b> as UI / UX. On the other hand the framework also works with its own Javascript library called <b>Roducks JS</b> which contains many utilities including Form validation, Modal box, Calendar, Datepicker, Local storage, Date formatting etc.
	</p>

		<div class="row">
			<div class="col-md-4">
				<h3>Architecture</h3>
				<ul>
					<li>Namespaces</li>
					<li>MVC Pattern</li>
					<li>Factory Pattern</li>
					<li>Dependency Injection</li>
					<li>ORM Pattern</li>
					<li>Class Autoload</li>
					<li>URL Rewrite (Htaccess)</li>
				</ul>
			</div>

			<div class="col-md-4">
				<h3>Features</h3>
				<ul>
					<li>Multilanguage</li>
					<li>Environments</li>
					<li>Email templates</li>
					<li>Output in (XML & JSON)</li>
					<li>Local storage</li>
					<li>Observers (Hooks)</li>
					<li>CLI Scripts</li>
				</ul>
			</div>
			<div class="col-md-4">
				<h3>More</h3>
				<ul>
					<li>Log In (BackEnd & FrontEnd)</li>
					<li>Users & Roles</li>
					<li>Error Debugger</li>
					<li>Query Pagination</li>
					<li>Subscribers</li>
					<li>Custom URLs</li>
					<li>Many more ...</li>
				</ul>
			</div>
		</div><!-- .row -->

	</div>

	<hr />

	<div class="text-centered">
		<h1>About the author</h1>
		<?php echo UI::getImage("rod.png"); ?>
		<br><br>
		<p>
			My name is <u><i>Rodrigo Cervantes</i></u> but friends call me <b>Rod</b>, I was born in Guadalajara, Mexico and I'm a Web Developer who loves to develop platforms, libraries and much more. I graduated from University in 2009, since then I've been working in different software companies in Mexico for the last years. I'm a PHP & Javascript lover since many years ago and of course I've worked with some popular frameworks in the past years for different kind of projects but since I consider myself very creative I like to create my own tools as well, so I'll be working on my ideas in the next years.
		</p>

		<h1>Why <?php echo UI::getImage("rdks_logo_black_mini.png"); ?> ?</h1>
		<p>The name came out in my mind because I like ducks and my name is <b>Rod</b>, so I mixed both in one, that's it. The reason why I decided to create <b>Roducks</b> is simple, I wanted to offer another solution to develop a Web Application with a new brand framework easy to use and few configurations to make work easier and as a result to avoid headaches on the road. I haven't gotten collaborations on the project so far but I'm open to get contributions in the near future.</p>

		<h1>{ Documentation }</h1>
		<p>I'll be working to provide an extensive and detailed documentation.</p>
		<?php echo UI::getImage("roducks_cup.jpg"); ?>
		<a target="_blank" href="https://github.com/rgocervantes/roducks">Go to Github</a>

		<h1>Thank you!</h1>
	</div>

</div>
