<?php
use Roducks\Page\Template;
use Roducks\Page\Block;
use Roducks\Framework\Login;
use Roducks\Framework\Language;
?>
<div class="container">
	<div class="box-white">

		<form id="foovar" name="foovar" method="post" 
		rel="rdks-form" 
		data-notification="true" 
		data-callback-success="cbFormSuccess" 
		data-callback-loading="cbFormLoading" 
		data-callback-error="cbFormError" 
	    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
	    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
	    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
		data-reset="false" 
		data-ajax="true" 
		data-json="true" 
		data-focus="true" 
		action="<?php echo "/_json/roles/{$action}"; ?>">

		<div class="well">
			<div class="row">
				<div class="col-xs-6">
					<?php if($edit): ?>
					<div class="form-group has-feedback<?php echo Template::conditional(!empty($_name), ' has-success','');  ?>">
					  <label class="control-label" for="_name"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_NAME; ?></label>
						<input type="text" class="form-control" value="<?php echo $_name; ?>" name="_name"
						rel="rdks-form-input-post" 
						data-helper="<?php echo TEXT_UNIQUE_NAME; ?>" 
						data-url="/_json/roles/name-taken" 
						data-required="true" 
						data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
						data-type="words" 
						data-alias="q" 
						<?php echo Template::conditional(!empty($_name), ' data-cache="'.$_name.'"',''); ?>
						/>
					  <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					  <span class="help-block"><?php echo TEXT_EXAMPLE; ?>: <b>Web editor</b></span>
					</div>
				<?php else: ?>
					<b><?php echo $_name; ?></b>
					<input type="hidden" name="_name" value="<?php echo $_name; ?>" />
				<?php endif; ?>
				</div>
			</div>
		</div>

		<input type="hidden" name="method" value="<?php echo $method; ?>" />
		<input type="hidden" name="config" value="<?php echo $config; ?>" />

		<div class="checkbox" style="margin:0;">
		    <label>
		      <input type="checkbox" rel="rdks-form-check-all" data-input=".checkbox-permissions"> <b><?php echo TEXT_ALL; ?></b> 
		    </label>
		</div>	
		
		<br>

		<?php Block::load("roles", ['config' => $data, 'type' => $type, 'access' => $access]); ?>

		<div class="checkbox" style="margin:0;">
		    <label>
		      <input type="checkbox" name="data[lock]" value="1" data-alert-warning="<?php echo Language::translate('Mark this option to continue', 'Marque esta opción para continuar'); ?>" data-required="true"> <span class="glyphicon glyphicon-lock" aria-hidden="true"></span> <?php echo Language::translate('Do you agree the changes?', '¿Está de acuerdo con los cambios?'); ?>
		    </label>
		</div>	
							
		<div style="height:60px;"></div>
		<nav class="navbar navbar-default navbar-fixed-bottom">
		  <div class="container">
		    <!-- Brand and toggle get grouped for better mobile display -->
		      <ul class="nav navbar-nav navbar-right">
		        <li class="dropdown_">
		          <div style="margin-right:200px;"><button type="submit" class="btn btn-lg btn-warning navbar-btn"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> <?php echo TEXT_SAVE; ?></button></div>	
		        </li>
		      </ul>
		    </div><!-- /.navbar-collapse -->
		  </div><!-- /.container-flrdks-formd -->
		</nav>	

		</form>
	</div>
</div>

