<?php
use Roducks\Page\Template;
use Roducks\Page\Block;
use Roducks\Framework\Helper;
use Roducks\Framework\Login;
?> 
<div class="container-fluid">
   <div class="box-white">
   		<?php Template::view("autocomplete"); ?>
		<table id="data-grid" width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover" data-url-visibility="/_json/roles/visibility">
			<tr>
				<th width="5%">ID</th>
				<th><?php echo TEXT_NAME; ?></th>
				<th width="5%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
			</tr>	
		<?php if($data->rows()): while($row = $data->fetch()): ?>
			<tr class="<?php echo Template::equals($row['active'], 0, 'row-disabled', ''); ?>">
				<td align="center"><?php echo $row['id_role']; ?></td>
				<td><?php echo $row['name']; ?></td>
				<td align="center">
					<?php if( isset($access['visibility']) || Login::isSuperAdmin() ): ?>

					<button type="button" class="btn rdks-ui-btn-<?php echo Template::equals($row['active'], 1,"enabled","disabled"); ?>" 
					rel="rdks-popOver"
					data-title="<?php echo TEXT_SURE; ?>" 
					data-callback="cbVisibility" 
					data-buttons='["No","<?php echo TEXT_YES; ?>"]'  
					data-value="<?php echo $row['active']; ?>" 
					data-id="<?php echo $row['id_role']; ?>" 
					data-params='{"type": 3}' 
					><span class="glyphicon glyphicon-eye-<?php echo Template::equals($row['active'], 1,"open","close"); ?>" aria-hidden="true"></span></button>

					<?php endif; ?>
				</td>
				<td align="center">
					<?php if( isset($access['edit']) || Login::isSuperAdmin() ): ?>
						<a href="/roles/edit/id/<?php echo $row['id_role']; ?>" class="btn btn-success"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
					<?php endif; ?>
				</td>
				<td align="center">
					<button type="button" onclick="modalRoles('<?php echo $row['name']; ?>','<?php echo Helper::removeFileExt($row['config']); ?>',<?php echo $row['type']; ?>);" class="btn btn-default"><span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></button>
				</td>
			</tr>
		<?php endwhile; else: ?>
			<tr>
				<td colspan="5">
					<div class="alert alert-warning" role="alert" style="margin:0;">
						<span class="alert-text">
							<span class="glyphicon glyphicon-alert" aria-hidden="true"></span> <?php echo TEXT_NO_RESULTS; ?>
						</span>
					</div>
				</td>
			</tr>
		<?php endif; ?>	
		</table>
	</div>
</div>
 
