<?php
use rdks\core\page\Template;
use rdks\core\page\Block;
use rdks\app\sites\admin\modules\Posts\helper\Posts as PostsHelper;

//\rdks\core\framework\Helper::pre(Block::getData("posts-categories")->getJson(['name' => "roducks"]));

//Block::load("posts-categories/listing", ['id' => 1251701, 'type' => "rdks_rod_71", 'values' => "name_acu00e9nto+con+eu00f1e"], ['x' => 923286]);

?>
<div class="container-fluid">
   <div class="box-white">
		<table id="data-grid" width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover" data-url-visibility="/_json/posts/visibility/category">
			<tr>
				<th width="5%">ID</th>
				<th><?php echo TEXT_NAME; ?></th>
				<th width="5%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
			</tr>	
		<?php if($data->rows()): while($row = $data->fetch()): ?>
			<tr class="<?php echo Template::equals($row['active'], 0, 'rdks-ui-row-disabled', ''); ?>">
				<td align="center"><?php echo $row['id_category']; ?></td>
				<td><a href="<?php echo PostsHelper::getPostsCategoryLink($row['id_category']); ?>"><?php echo $row['title']; ?> (<?php echo PostsHelper::stGetTotalPostsByCategoryId($row['id_category'], false); ?>)</a></td>
				<td align="center">
					
					<button type="button" class="btn rdks-ui-btn-<?php echo Template::equals($row['active'], 1,"enabled","disabled"); ?>" 
					rel="rdks-popOver"
					data-title="<?php echo TEXT_SURE; ?>" 
					data-callback="cbVisibility" 
					data-buttons='["No","<?php echo TEXT_YES; ?>"]'  
					data-value="<?php echo $row['active']; ?>" 
					data-id="<?php echo $row['id_category']; ?>" 
					><span class="glyphicon glyphicon-eye-<?php echo Template::equals($row['active'], 1,"open","close"); ?>" aria-hidden="true"></span></button>

				</td>
				<td align="center">
					<a href="<?php echo PostsHelper::getEditCategoryLink($row['id_category']); ?>" class="btn btn-success"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
				</td>
				<td align="center">
					<a href="<?php echo PostsHelper::getAddPostLink($row['id_category']); ?>" class="btn btn-warning"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></a>
				</td>
			</tr>
		<?php endwhile; else: ?>
			<tr>
				<td colspan="5">
					<div class="alert alert-warning" role="alert" style="margin:0;">
						<span class="alert-text">
							<span class="glyphicon glyphicon-alert" aria-hidden="true"></span> <?php echo TEXT_NO_RESULTS; ?>
						</span>
					</div>
				</td>
			</tr>
		<?php endif; ?>	
		</table>
	</div>
</div>
 
