<?php
use rdks\core\page\Template;
use rdks\core\framework\Language;
?>
<div class="container">
	<?php Template::view("btn-back"); ?>
	<br><br>
	<div class="box-white">
		<?php Template::view("title"); ?>
		<div class="row">
			<div class="col-xs-6">

				<form id="foovar" name="foovar" method="post" 
				rel="rdks-form" 
				data-notification="true" 
				data-callback-success="cbFormSuccess" 
				data-callback-loading="cbFormLoading" 
				data-callback-error="cbFormError" 
			    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
			    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
			    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
				data-reset="<?php echo Template::conditional($edit,'false','true'); ?>" 
				data-ajax="true" 
				data-json="true" 
				data-focus="true" 
				action="<?php echo "/_json{$url}/{$action}"; ?>">

					<div class="checkbox">
						<label>
						<input<?php echo Template::checked($row['active']); ?> type="checkbox" name="active" value="1" /> 
						<?php echo TEXT_ACTIVE; ?></label>
					</div>

					<div class="form-group has-feedback">
						<label class="control-label" for="title"><span class="rdks-ui-color-red">*</span> <?php echo Language::translate("Title", "Título"); ?></label>
						<input type="text" name="title" class="form-control" 
						data-required="true" 
						data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
						data-type="words" 
						value="<?php echo $row['title']; ?>"
						/>
						<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
						<span class="help-block"></span>
					</div>

					<button type="submit" class="btn btn-lg btn-warning navbar-btn">
						<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> <?php echo TEXT_SAVE; ?>
					</button>

				</form>

			</div>
		</div>
	</div>
</div>
