<?php
use rdks\core\page\Template;
use rdks\app\sites\admin\modules\Posts\helper\Posts as PostsHelper;
?> 
<div class="container-fluid">
   <div class="box-white">
		<table id="data-grid" width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover" data-url-visibility="/_json/posts/visibility/post">
			<tr>
				<th width="5%">ID</th>
				<th><?php echo TEXT_NAME; ?></th>
				<th width="5%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
				<th width="5%">&nbsp;</th>
			</tr>	
		<?php if($data->rows()): while($row = $data->fetch()): ?>
			<tr class="<?php echo Template::equals($row['active'], 0, 'rdks-ui-row-disabled', ''); ?>">
				<td align="center"><?php echo $row['postId']; ?></td>
				<td><a href="<?php echo PostsHelper::getEditPostLink($row['postId']); ?>"><?php echo $row['title']; ?></a></td>
				<td align="center">
					
					<button type="button" class="btn rdks-ui-btn-<?php echo Template::equals($row['active'], 1,"enabled","disabled"); ?>" 
					rel="rdks-popOver"
					data-title="<?php echo TEXT_SURE; ?>" 
					data-callback="cbVisibility" 
					data-buttons='["No","<?php echo TEXT_YES; ?>"]'  
					data-value="<?php echo $row['active']; ?>" 
					data-id="<?php echo $row['postId']; ?>" 
					><span class="glyphicon glyphicon-eye-<?php echo Template::equals($row['active'], 1,"open","close"); ?>" aria-hidden="true"></span></button>

				</td>
				<td align="center">
					<a href="<?php echo PostsHelper::getEditPostLink($row['postId']); ?>" class="btn btn-success"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
				</td>
				<td align="center">
					<a href="<?php echo PostsHelper::getPostPublicLink($row['postId']); ?>" target="_blank" class="btn btn-default"><span class="glyphicon glyphicon-new-window" aria-hidden="true"></span></a>
				</td>
			</tr>
		<?php endwhile; else: ?>
			<tr>
				<td colspan="5">
					<div class="alert alert-warning" role="alert" style="margin:0;">
						<span class="alert-text">
							<span class="glyphicon glyphicon-alert" aria-hidden="true"></span> <?php echo TEXT_NO_RESULTS; ?>
						</span>
					</div>
				</td>
			</tr>
		<?php endif; ?>	
		</table>
	</div>
</div>
 
