<?php
use rdks\core\page\Template;
?>
<div class="container">
	<br>
	<div class="row">
		<div class="col-xs-6">
			<h1><?php echo TEXT_EDIT . " " . TEXT_DATA; ?></h1>

			<form id="foovar" name="foovar" method="post" 
			rel="rdks-form" 
			data-notification="true" 
			data-callback-success="<?php echo Template::equals($action,'insert','cbFormUsersSuccess','cbFormRedirectSuccess'); ?>" 
			data-callback-loading="cbFormLoading" 
			data-callback-error="cbFormError" 
		    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
		    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
		    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
			data-reset="<?php echo Template::conditional($edit,'false','true'); ?>" 
			data-ajax="true" 
			data-json="true" 
			data-focus="true" 
			action="<?php echo "/_json/account/update"; ?>">

			<div class="form-group has-feedback">
				<label class="control-label" for="first_name"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_FIRST_NAME; ?></label>
				<input type="text" name="first_name" class="form-control" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="words" 
				value="<?php echo $first_name; ?>"
				/>
				<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				<span class="help-block"></span>
			</div>

			<div class="form-group has-feedback">
				<label class="control-label" for="last_name"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_LAST_NAME; ?></label>
				<input type="text" name="last_name" class="form-control" 
				data-required="true" 
				data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
				data-type="words" 
				value="<?php echo $last_name; ?>"
				/>
				<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				<span class="help-block"></span>
			</div>
			  
			<button type="submit" class="btn btn-lg btn-warning navbar-btn">
				<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> <?php echo TEXT_SAVE; ?>
			</button>

			</form>

		</div>
	</div>

</div>
