<?php

use rdks\core\framework\Path;

?>
<div class="container">
  <div id="login-box" style="display:none;">
     <div style="width:540px; margin:0 auto;"> 

      <div style="width:357px; margin:0 auto;"><img src="<?php echo Path::getLogo(); ?>"></div>

    <form id="auth" name="auth" method="post" 
    rel="rdks-form" 
    data-notification="true" 
    data-notification-hide="false" 
    data-callback-success="cbFormSuccess" 
    data-callback-loading="cbFormLoading" 
    data-callback-error="cbFormError" 
    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
    data-reset="true" 
    data-ajax="true" 
    data-json="true" 
    data-focus="true" 
    action="/auth"
    >
     
  <div class="form-group has-feedback">
    <label class="control-label" for="email">Email</label>
    <input type="text" name="email" class="form-control" 
    data-required="true" 
    data-alert-warning="" 
    data-alert-error="<?php echo TEXT_INVALID_EMAIL; ?>" 
    data-type="email" />
    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
    <span class="help-block"></span>
  </div>

  <div class="form-group has-feedback">
    <label class="control-label" for="password"><?php echo TEXT_PASSWORD; ?></label>
    <input type="password" name="password" class="form-control" 
    data-required="true" 
    data-alert-warning="" 
    data-minlength="1|"     
    data-type="password"
    />

    <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
    <span class="help-block"></span>
  </div>

  <div class="text-centered">
    <button type="submit" name="sender" class="btn btn-lg btn-rdks">
      <span class="glyphicon glyphicon-lock" aria-hidden="true"></span> <?php echo TEXT_LOGIN; ?>
    </button>
    <hr />
    <a href="/account/forgotten-password" ><?php echo TEXT_FORGOTTEN_PASSWORD; ?></a> | <a href="/account/create" ><?php echo TEXT_CREATE_ACCOUNT; ?></a>
  </div>
    </form>

    </div>
  </div>
</div>