	<div id="btn-crop" class="display-none">
		<form name="foo" method="post" 
		rel="rdks-form" 
		data-ajax="true" 
		data-json="true" 
		data-reset="true" 
		data-callback-success="cbCropSuccess" 
		data-callback-loading="cbFormLoading" 
		data-callback-error="cbCropError" 
		action="/_service/file-ajax/module/<?php echo $module; ?>/<?php echo $config; ?>/crop-squared">
			<input type="hidden" id="x" name="x" />
			<input type="hidden" id="y" name="y" />
			<input type="hidden" id="w" name="w" />
			<input type="hidden" id="h" name="h" />
			<input type="hidden" id="dir" name="dir" />
			<input type="hidden" id="img" name="cropper" />
			<input type="hidden" name="copy" value="<?php echo $picture; ?>" />
			<button class="btn btn-lg btn-danger"><span class="glyphicon glyphicon-scissors" aria-hidden="true"></span> <?php echo TEXT_CROP; ?></button>
		</form>
	</div>

	<div id="btn-upload-box" class="left">
		<button id="btn-upload" type="button" class="btn btn-lg btn-success btn-upload">
			<span class="glyphicon glyphicon-open" aria-hidden="true"></span> <?php echo TEXT_UPLOAD; ?>
		</button>
	</div>
	<div class="clear"></div>
	
	<br>
	<div id="crop"></div>