<?php 
use rdks\core\page\Template; 
use rdks\core\framework\Language;
use rdks\app\sites\shop\modules\Cart\helper\Cart as CartHelper;

$cartHelper = CartHelper::init();

?>
<h1><?php echo $title; ?></h1>

<div class="checkbox">
  <label>
  	<?php if($sameAdress): ?>
    <input type="checkbox" id="same-address" name="same_address" value="#<?php echo $field; ?>"<?php echo Template::checked((isset($address['same_address']))); ?>/>
    <?php echo Language::translate("The same than shipping address","Misma que la Dirección de Envío"); ?>
	<?php else: ?>
		&nbsp;
    <?php endif; ?>
  </label>
</div>

<div id="<?php echo $field; ?>" style="display: <?php echo Template::conditional((isset($address['same_address']) && $sameAdress), 'none', 'block'); ?>">

	<label class="control-label"><?php echo Language::translate("Personal Data","Datos Personales"); ?></label>
	<div class="well">

		<div class="form-group has-feedback">
			<label class="control-label"><?php echo Language::translate("First Name","Nombre"); ?></label>
			<input type="text" name="<?php echo $field; ?>[first_name]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="words" value="<?php echo (isset($address[$field]['first_name'])) ? $address[$field]['first_name'] : ''; ?>" />
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>
		</div>

		<div class="form-group has-feedback">
			<label class="control-label"><?php echo Language::translate("Last Name","Apellidos"); ?></label>
			<input type="text" name="<?php echo $field; ?>[last_name]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="words" value="<?php echo (isset($address[$field]['last_name'])) ? $address[$field]['last_name'] : ''; ?>" />
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>
		</div>

		<div class="form-group has-feedback">
			<label class="control-label"><?php echo Language::translate("Email","Email"); ?></label>
			<input type="text" name="<?php echo $field; ?>[email]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>" data-alert-error="<?php echo Language::translate("Invalid Email","Email inválido"); ?>" data-type="email" value="<?php echo (isset($address[$field]['email'])) ? $address[$field]['email'] : ''; ?>" />
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>
		</div>

		<div class="form-group has-feedback">
			<label class="control-label"><?php echo Language::translate("RFC","RFC"); ?></label>
			<input type="text" name="<?php echo $field; ?>[rfc]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="code" value="<?php echo (isset($address[$field]['rfc'])) ? $address[$field]['rfc'] : ''; ?>" />
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>
		</div>

	</div>	

	<label class="control-label"><?php echo Language::translate("Address","Dirección"); ?></label>
	<div class="well">

		<div class="form-group has-feedback<?php echo (isset($address[$field.'_country'])) ? ' has-success' : ''; ?>">
			<label class="control-label"><?php echo Language::translate("Country","País"); ?></label>
			<input type="hidden" name="<?php echo $field; ?>_country" class="form-control filter-<?php echo $field; ?>" 
			data-text="<?php echo (isset($address[$field.'_country'])) ? CartHelper::select($address[$field.'_country']) : Language::translate("Select a option","Selecciona una opción"); ?>" 
			data-label="<?php echo Language::translate("Select a option","Selecciona una opción"); ?>" 
			data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
			data-required="true" 
			data-text-results="<?php echo TEXT_NO_RESULTS; ?>" 
			data-callback="cbCountry" 
			rel="rdks-form-dropdown" 
			value="<?php echo (isset($address[$field.'_country'])) ? $address[$field.'_country'] : ''; ?>"
			/>
			
	        <div id="<?php echo $field; ?>_country-data" style="display:none;">
	            <ul>
	            	<?php foreach($countries as $country): ?>
	                <li class="active<?php echo Template::conditional((isset($address[$field.'_country']) && $address[$field.'_country'] == $country['id']),' selected')?>" style="display: list-item;">
	                    <a href="javascript:;" data-text="<?php echo $country['name']; ?>" onclick="cbFilterChoice('<?php echo $field; ?>_country', '<?php echo $country['name']; ?>', <?php echo $country['id']; ?>, {&quot;field&quot;:&quot;<?php echo $field; ?>&quot;});"><span class="speller"><?php echo $country['name']; ?></span></a>
	                </li>
					<?php endforeach; ?>
	            </ul>
			</div><!-- .listing -->

		</div><!-- countries -->

		<div class="form-group has-feedback<?php echo (isset($address[$field.'_state'])) ? ' has-success' : ''; ?>">
			<label class="control-label"><?php echo Language::translate("State","Estado"); ?></label>
			<input type="<?php echo Template::conditional((empty($states)),'text','hidden'); ?>" name="<?php echo $field; ?>_state"  class="form-control filter-<?php echo $field; ?>" 
			data-text="<?php echo (isset($address[$field.'_state'])) ? CartHelper::select($address[$field.'_state']) : Language::translate("Select a option","Selecciona una opción"); ?>" 
			data-label="<?php echo Language::translate("Select a option","Selecciona una opción"); ?>" 
			data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
			data-required="true" 
			data-text-results="<?php echo TEXT_NO_RESULTS; ?>" 
			data-callback="cbState" 
			data-disabled="<?php echo (isset($address[$field.'_state'])) ? 'false' : 'true'; ?>" 
			rel="rdks-form-dropdown" 
			value="<?php echo (isset($address[$field.'_state'])) ? $address[$field.'_state'] : ''; ?>"
			/>
			
	        <div id="<?php echo $field; ?>_state-data" style="display:none;">
	            <ul>
	            	<?php if(isset($address[$field.'_state'])): foreach($states as $state): ?>
	                <li class="active<?php echo Template::conditional((isset($address[$field.'_state']) && $address[$field.'_state'] == $state['id']),' selected')?>" style="display: list-item;">
	                    <a href="javascript:;" data-text="<?php echo $state['name']; ?>" onclick="cbFilterChoice('<?php echo $field; ?>_state', '<?php echo $state['name']; ?>', <?php echo $state['id']; ?>, {&quot;field&quot;:&quot;<?php echo $field; ?>&quot;});"><span class="speller"><?php echo $state['name']; ?></span></a>
	                </li>
	           		<?php endforeach; endif; ?>
	            </ul>
			</div><!-- .listing -->

		</div><!-- states -->

		<div class="form-group has-feedback<?php echo (isset($address[$field.'_city'])) ? ' has-success' : ''; ?>">
			<label class="control-label"><?php echo Language::translate("City","Municipio / Delegación / Ciudad"); ?></label>
			<input type="<?php echo Template::conditional((empty($cities)),'text','hidden'); ?>" name="<?php echo $field; ?>_city" class="form-control filter-<?php echo $field; ?>" 
			data-text="<?php echo (isset($address[$field.'_city'])) ? CartHelper::select($address[$field.'_city']) : Language::translate("Select a option","Selecciona una opción"); ?>" 
			data-label="<?php echo Language::translate("Select a option","Selecciona una opción"); ?>" 
			data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
			data-required="true" 
			data-text-results="<?php echo TEXT_NO_RESULTS; ?>" 
			data-callback="cbCity" 
			data-disabled="<?php echo (isset($address[$field.'_city'])) ? 'false' : 'true'; ?>" 
			rel="rdks-form-dropdown" 
			onblur="$rdks.checkout.blur(this);" 
			value="<?php echo (isset($address[$field.'_city'])) ? $address[$field.'_city'] : ''; ?>"
			/>
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>			
			
	        <div id="<?php echo $field; ?>_city-data" style="display:none;">
	            <ul>
	            	<?php if(isset($address[$field.'_city'])): foreach($cities as $city): ?>
	                <li class="active<?php echo Template::conditional((isset($address[$field.'_city']) && $address[$field.'_city'] == $city['id']),' selected')?>" style="display: list-item;">
	                    <a href="javascript:;" data-text="<?php echo $city['name']; ?>" onclick="cbFilterChoice('<?php echo $field; ?>_city', '<?php echo $city['name']; ?>', <?php echo $city['id']; ?>, {&quot;field&quot;:&quot;<?php echo $field; ?>&quot;});"><span class="speller"><?php echo $city['name']; ?></span></a>
	                </li>
	           		<?php endforeach; endif; ?>
	            </ul>
			</div><!-- .listing -->

		</div><!-- states -->

		<div class="form-group has-feedback">
			<label class="control-label"><?php echo Language::translate("Suburb","Colonia"); ?></label>
			<input type="text" name="<?php echo $field; ?>[suburb]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="words" value="<?php echo (isset($address[$field]['suburb'])) ? $address[$field]['suburb'] : ''; ?>" />
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>
		</div>

		<div class="form-group has-feedback">
			<label class="control-label"><?php echo Language::translate("Street","Calle"); ?></label>
			<input type="text" name="<?php echo $field; ?>[street_name]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="words" value="<?php echo (isset($address[$field]['street_name'])) ? $address[$field]['street_name'] : ''; ?>" />
			<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
			<span class="help-block"></span>
		</div>

		<div class="row">
			<div class="col-md-6">
				<div class="form-group has-feedback">
					<label class="control-label"><?php echo Language::translate("Number","No."); ?></label>
					<input type="text" name="<?php echo $field; ?>[street_number]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="$rdks.checkout.fillBilling(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="int" value="<?php echo (isset($address[$field]['street_number'])) ? $address[$field]['street_number'] : ''; ?>" />
					<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					<span class="help-block"></span>
				</div>
			</div>
			<div class="col-md-6">
				<div class="form-group has-feedback">
					<label class="control-label"><?php echo Language::translate("Postal Code","Código Postal"); ?></label>
					<input type="text" name="<?php echo $field; ?>[postal_code]" class="form-control <?php echo $field; ?>"<?php echo Template::equals($field,'shipping',' onblur="cbPostalCode(this);"'); ?> data-required="true" data-alert-warning="<?php echo TEXT_REQUIRED; ?>"  data-type="int" value="<?php echo (isset($address[$field]['postal_code'])) ? $address[$field]['postal_code'] : ''; ?>" />
					<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					<span class="help-block"></span>
				</div>
			</div>
		</div>

		<?php if($field == 'shipping'): ?>
		<div style="opacity: 0; overflow: hidden; height:0;">
			<input id="lock" type="text" name="lock" data-required="true" value="<?php echo (isset($address['lock'])) ? $address['lock'] : ''; ?>" />
		</div>
		<?php endif; ?>
	</div>

</div>
					