<?php
use rdks\core\page\Block;
?>
<div class="container-fluid">
	<?php if($hasItems): ?>
	<div class="right"><a href="/cart/empty"><h1><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></h1></a></div>
	<div class="right"><h1><span style="margin:0 15px;">|</span></h1></div>
	<?php endif; ?>
	<div id="rdks-cart-counter" class="right"><?php Block::load("cart/counter"); ?></div>
	<div class="clear"></div>
	<?php Block::load("cart/items"); ?>
</div>