<?php
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 *	-----------------
 *	English Texts
 *	-----------------
 */

use rdks\core\framework\Core;

Core::define('TEXT_WELCOME', "Welcome");
Core::define('TEXT_WELCOME_TO', TEXT_WELCOME . " to");
Core::define('TEXT_CREATED_ON', "Created on");
Core::define('TEXT_PARENT', "Parent");
Core::define('TEXT_ROLE', "Role");
Core::define('TEXT_TREE', "Tree");
Core::define('TEXT_DATA', "Data");
Core::define('TEXT_DATE', "Date");
Core::define('TEXT_TIME', "Time");
Core::define('TEXT_RESET', "Reset");
Core::define('TEXT_SEARCH', "Search");
Core::define('TEXT_DESCENDANTS', "Descendants");
Core::define('TEXT_START_DATE', "Start date");
Core::define('TEXT_END_DATE', "End date");
Core::define('TEXT_ENTRANCES', "Entrances");
Core::define('TEXT_DEPARTURES', "Departures");
Core::define('TEXT_LANGUAGES', "Languages");
Core::define('TEXT_NOT_FOUND', "Not Found");
Core::define('TEXT_FILE', "File");
Core::define('TEXT_SERVICE_UNAVAILABLE', "Service unavailable.");
Core::define('TEXT_LOGGED_IN_STRANGER', "Someone was logged in your account moments ago.");
Core::define('TEXT_FILTERED_RESULT', "Filtered result.");
Core::define('TEXT_WAS_AN_ERROR', "There was an error");
Core::define('TEXT_UNIQUE_NAME', "Choose an unique name.");
Core::define('TEXT_AUTH_OK', "Auth OK!");
Core::define('TEXT_AUTH_FAIL', "Email or Password are incorrect");
Core::define('TEXT_AUTH_DISABLED', "Your account was disabled.");
Core::define('TEXT_USER_NOT_EXIST', "User does not exist");
Core::define('TEXT_INVALID_REQUEST', "Invalid request");
Core::define('TEXT_CHANGES_SAVED', "Data was saved successfully.");
Core::define('TEXT_GRANT_ACCESS_REQUIRED', "You don't have enough permissions to do this action.");
Core::define('TEXT_BACK', "Back");
Core::define('TEXT_CLOSE', "Close");
Core::define('TEXT_ALL', "All");
Core::define('TEXT_NAME', "Name");
Core::define('TEXT_EXAMPLE', "Example");
Core::define('TEXT_TRASH', "Trash");
Core::define('TEXT_SURE', "Are you sure?");
Core::define('TEXT_YES', "Yes");
Core::define('TEXT_COMMENT', "Comment");
Core::define('TEXT_CONTACT_US', "Contact Us");
Core::define('TEXT_GO_TO', "Go to");
Core::define('TEXT_EXPIRED', "Expired");
Core::define('TEXT_EXPIRATION_DATE', "Expiration Date");
Core::define('TEXT_EXPIRES', "Expires");
Core::define('TEXT_ONE_MOMENT_PLEASE', "One moment please.");
Core::define('TEXT_UNAVAILABLE_ROLE', "Unavailable Role.");
Core::define('TEXT_PAGE_NOT_FOUND', "Page Not Found");
Core::define('TEXT_CHOOSE_AN_OPTION', "Choose an option.");
Core::define('TEXT_LATEST', "Latest");
Core::define('TEXT_FULL_NAME', "Full name");
Core::define('TEXT_VIEW', "View");
Core::define('TEXT_ENABLE_DISABLE', "Active / Unactive");
Core::define('TEXT_MANAGE_DESCENDANTS', "Manage only direct descendants");
Core::define('TEXT_MANAGE_TREE_DESCENDANTS', "Manage all descendants");
Core::define('TEXT_MANAGE_TREE_DESCENDANTS_DESC', "He will be able to manage users created by himself and by his children.");
Core::define('TEXT_MANAGE_DESCENDANTS_DESC', "He will be able to manage only users created by himself.");
Core::define('TEXT_LOGIN', "Log In");
Core::define('TEXT_LOGOUT', "Log Out");
Core::define('TEXT_USER_PASSWORD_REQUIRED', "Email & Password are required.");
Core::define('TEXT_PASSWORD', "Password");
Core::define('TEXT_REQUIRED', "It's required");
Core::define('TEXT_INVALID_EMAIL', "Invalid Email");
Core::define('TEXT_MIN_LENGTH', "Length must be minimium 7 characteres");
Core::define('TEXT_FORM_WARNING', "Please fill out the required fields *");
Core::define('TEXT_FORM_ERROR', "There were found errors.");
Core::define('TEXT_FORM_FAILED', "Server does not respond, Try again later.");
Core::define('TEXT_FORGOTTEN_PASSWORD', "Forgot password?");
Core::define('TEXT_INCORRECT_PASSWORD', "Password is incorrect.");
Core::define('TEXT_ACCOUNT', "Account");
Core::define('TEXT_EDIT_ACCOUNT', "Edit account");
Core::define('TEXT_PROFILE_PICTURE', "Profile picture");
Core::define('TEXT_CHANGE_PASSWORD', "Change password");
Core::define('TEXT_NEW_PASSWORD', "New password");
Core::define('TEXT_CURRENT_PASSWORD', "Current password");
Core::define('TEXT_RESET_PASSWORD', "Reset password");
Core::define('TEXT_CREATE_ACCOUNT', "Create account");
Core::define('TEXT_APP_IN_DEV_MODE', "App's running in development mode");
Core::define('TEXT_USER', "User");
Core::define('TEXT_USERS', "Users");
Core::define('TEXT_SUBSCRIBERS', "Subscribers");
Core::define('TEXT_CLIENTS', "Clients");
Core::define('TEXT_SUPPLIERS', "Suppliers");
Core::define('TEXT_PICTURE', "Picture");
Core::define('TEXT_NO_RESULTS', "There are no results.");
Core::define('TEXT_PAGE', "Page");
Core::define('TEXT_CREATE', "Create");
Core::define('TEXT_NEW', "New");
Core::define('TEXT_EDIT', "Edit");
Core::define('TEXT_SAVE', "Save");
Core::define('TEXT_UPDATE', "Update");
Core::define('TEXT_SUBMIT', "Submit");
Core::define('TEXT_GENDER', "Gender");
Core::define('TEXT_MALE', "Man");
Core::define('TEXT_FEMALE', "Woman");
Core::define('TEXT_UPLOAD', "Upload");
Core::define('TEXT_CROP', "Crop");
Core::define('TEXT_FIRST_NAME', "First name");
Core::define('TEXT_LAST_NAME', "Last name");
Core::define('TEXT_CONFIRM_PASSWORD', "Confirm password");
Core::define('TEXT_PASSWORD_NO_MATCH', "Password does not match.");
Core::define('TEXT_RECOVER_PASSWORD', "Recover password");
Core::define('TEXT_ERROR_SENDING_EMAIL', "It couldn't be sent email.");
Core::define('TEXT_ERROR_CREATING_USER', "It couldn't be created user, Try again later.");
Core::define('TEXT_ERROR_RESETING_PASSWORD', "It couldn't reset password.");
Core::define('TEXT_FORM_ERRORS', "Form has errors.");
