<?php
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 *	-----------------
 *	English Texts
 *	-----------------
 */

App::text('TO', "To");
App::text('For', "For");
App::text('From', "From");
App::text('WELCOME', "Welcome");
App::text('WELCOME_TO', TEXT_WELCOME . " to");
App::text('CREATED_ON', "Created on");
App::text('PARENT', "Parent");
App::text('ROLE', "Role");
App::text('TREE', "Tree");
App::text('DATA', "Data");
App::text('DATE', "Date");
App::text('TIME', "Time");
App::text('YEAR', "Year");
App::text('MONTH', "Month");
App::text('PREVIOUS', "Previous");
App::text('NEXT', "Next");
App::text('FILTER', "Filter");
App::text('TO_FILTER', "Filter");
App::text('RESET', "Reset");
App::text('SEARCH', "Search");
App::text('TO_SEARCH', "Search");
App::text('DESCENDANTS', "Descendants");
App::text('START_DATE', "Start date");
App::text('END_DATE', "End date");
App::text('ENTRANCES', "Entrances");
App::text('DEPARTURES', "Departures");
App::text('LANGUAGES', "Languages");
App::text('NOT_FOUND', "Not Found");
App::text('FILE', "File");
App::text('SERVICE_UNAVAILABLE', "Service unavailable.");
App::text('LOGGED_IN_STRANGER', "Someone was logged in your account moments ago.");
App::text('FILTERED_RESULT', "Filtered result.");
App::text('WAS_AN_ERROR', "There was an error");
App::text('UNIQUE_NAME', "Choose an unique name.");
App::text('AUTH_OK', "Auth OK!");
App::text('AUTH_FAIL', "Email or Password are incorrect");
App::text('AUTH_DISABLED', "Your account was disabled.");
App::text('USER_NOT_EXIST', "User does not exist");
App::text('INVALID_REQUEST', "Invalid request");
App::text('CHANGES_SAVED', "Data was saved successfully.");
App::text('GRANT_ACCESS_REQUIRED', "You don't have enough permissions to do this action.");
App::text('BACK', "Back");
App::text('CLOSE', "Close");
App::text('ALL', "All");
App::text('NAME', "Name");
App::text('EXAMPLE', "Example");
App::text('TRASH', "Trash");
App::text('SURE', "Are you sure?");
App::text('YES', "Yes");
App::text('COMMENT', "Comment");
App::text('CONTACT_US', "Contact Us");
App::text('GO_TO', "Go to");
App::text('EXPIRED', "Expired");
App::text('EXPIRATION_DATE', "Expiration Date");
App::text('EXPIRES', "Expires");
App::text('ONE_MOMENT_PLEASE', "One moment please.");
App::text('UNAVAILABLE_ROLE', "Unavailable Role.");
App::text('PAGE_NOT_FOUND', "Page Not Found");
App::text('CHOOSE_AN_OPTION', "Choose an option.");
App::text('LATEST', "Latest");
App::text('FULL_NAME', "Full name");
App::text('VIEW', "View");
App::text('ACTIVE', "Active");
App::text('ENABLE_DISABLE', "Active / Unactive");
App::text('MANAGE_DESCENDANTS', "Manage only direct descendants");
App::text('MANAGE_TREE_DESCENDANTS', "Manage all descendants");
App::text('MANAGE_TREE_DESCENDANTS_DESC', "He will be able to manage users created by himself and by his children.");
App::text('MANAGE_DESCENDANTS_DESC', "He will be able to manage only users created by himself.");
App::text('LOGIN', "Log In");
App::text('LOGOUT', "Log Out");
App::text('USER_PASSWORD_REQUIRED', "Email & Password are required.");
App::text('PASSWORD', "Password");
App::text('REQUIRED', "It's required");
App::text('INVALID_EMAIL', "Invalid Email");
App::text('MIN_LENGTH', "Length must be minimium 7 characteres");
App::text('FORM_WARNING', "Please fill out the required fields *");
App::text('FORM_ERROR', "There were found errors.");
App::text('FORM_FAILED', "Server does not respond, Try again later.");
App::text('FORGOTTEN_PASSWORD', "Forgot password?");
App::text('INCORRECT_PASSWORD', "Password is incorrect.");
App::text('ACCOUNT', "Account");
App::text('EDIT_ACCOUNT', "Edit account");
App::text('PROFILE_PICTURE', "Profile picture");
App::text('CHANGE_PASSWORD', "Change password");
App::text('NEW_PASSWORD', "New password");
App::text('CURRENT_PASSWORD', "Current password");
App::text('RESET_PASSWORD', "Reset password");
App::text('CREATE_ACCOUNT', "Create account");
App::text('APP_IN_DEV_MODE', "App's running in development mode");
App::text('USER', "User");
App::text('USERS', "Users");
App::text('SUBSCRIBERS', "Subscribers");
App::text('CLIENTS', "Clients");
App::text('SUPPLIERS', "Suppliers");
App::text('PICTURE', "Picture");
App::text('NO_RESULTS', "There are no results.");
App::text('PAGE', "Page");
App::text('CREATE', "Create");
App::text('NEW', "New");
App::text('EDIT', "Edit");
App::text('SAVE', "Save");
App::text('UPDATE', "Update");
App::text('SUBMIT', "Submit");
App::text('GENDER', "Gender");
App::text('MALE', "Man");
App::text('FEMALE', "Woman");
App::text('UPLOAD', "Upload");
App::text('CROP', "Crop");
App::text('CONTENT', "Content");
App::text('FIRST_NAME', "First name");
App::text('LAST_NAME', "Last name");
App::text('CONFIRM_PASSWORD', "Confirm password");
App::text('PASSWORD_NO_MATCH', "Password does not match.");
App::text('RECOVER_PASSWORD', "Recover password");
App::text('ERROR_SENDING_EMAIL', "It couldn't be sent email.");
App::text('ERROR_CREATING_USER', "It couldn't be created user, Try again later.");
App::text('ERROR_RESETING_PASSWORD', "It couldn't reset password.");
App::text('FORM_ERRORS', "Form has errors.");
