<?php
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 *	-----------------
 *	Spanish Texts
 *	-----------------
 */

use rdks\core\framework\Core;

Core::define('TEXT_WELCOME', "Bienvenido");
Core::define('TEXT_WELCOME_TO', TEXT_WELCOME . " a");
Core::define('TEXT_CREATED_ON', "Creado el");
Core::define('TEXT_PARENT', "Padre");
Core::define('TEXT_ROLE', "Rol");
Core::define('TEXT_TREE', "Árbol");
Core::define('TEXT_DATA', "Datos");
Core::define('TEXT_DATE', "Fecha");
Core::define('TEXT_TIME', "Hora");
Core::define('TEXT_RESET', "Restablecer");
Core::define('TEXT_SEARCH', "Búsqueda");
Core::define('TEXT_DESCENDANTS', "Descendencia");
Core::define('TEXT_START_DATE', "Fecha inicio");
Core::define('TEXT_END_DATE', "Fecha fin");
Core::define('TEXT_ENTRANCES', "Entradas");
Core::define('TEXT_DEPARTURES', "Salidas");
Core::define('TEXT_LANGUAGES', "Idiomas");
Core::define('TEXT_NOT_FOUND', "No encontrado");
Core::define('TEXT_FILE', "Archivo");
Core::define('TEXT_SERVICE_UNAVAILABLE', "Servicio no disponible.");
Core::define('TEXT_LOGGED_IN_STRANGER', "Alguien estaba usando su cuenta en este momento.");
Core::define('TEXT_FILTERED_RESULT', "Resultado filtrado.");
Core::define('TEXT_WAS_AN_ERROR', "Ocurrió un error.");
Core::define('TEXT_UNIQUE_NAME', "Elige un nombre único.");
Core::define('TEXT_AUTH_OK', "Autenticación exitosa!");
Core::define('TEXT_AUTH_FAIL', "Email o contraseña son incorrectos");
Core::define('TEXT_AUTH_DISABLED', "Tu cuenta fue desactivada.");
Core::define('TEXT_USER_NOT_EXIST', "El usuario no existe");
Core::define('TEXT_INVALID_REQUEST', "Solicitud inválida");
Core::define('TEXT_CHANGES_SAVED', "Los cambios fueron guardados con éxito.");
Core::define('TEXT_GRANT_ACCESS_REQUIRED', "No tiene permisos suficientes para realizar esta operación.");
Core::define('TEXT_BACK', "Atrás");
Core::define('TEXT_CLOSE', "Cerrar");
Core::define('TEXT_ALL', "Todos");
Core::define('TEXT_NAME', "Nombre");
Core::define('TEXT_EXAMPLE', "Ejemplo");
Core::define('TEXT_TRASH', "Papelera");
Core::define('TEXT_SURE', "¿Está seguro?");
Core::define('TEXT_YES', "Si");
Core::define('TEXT_COMMENT', "Comentario");
Core::define('TEXT_CONTACT_US', "Contacto");
Core::define('TEXT_GO_TO', "Ir a");
Core::define('TEXT_EXPIRED', "Expiró");
Core::define('TEXT_EXPIRATION_DATE', "Fecha de Expiración");
Core::define('TEXT_EXPIRES', "Expira");
Core::define('TEXT_ONE_MOMENT_PLEASE', "Un momento por favor.");
Core::define('TEXT_UNAVAILABLE_ROLE', "Rol no disponible.");
Core::define('TEXT_PAGE_NOT_FOUND', "Página No Encontrada");
Core::define('TEXT_CHOOSE_AN_OPTION', "Elige una opción.");
Core::define('TEXT_LATEST', "Últimos");
Core::define('TEXT_FULL_NAME', "Nombre");
Core::define('TEXT_VIEW', "Ver");
Core::define('TEXT_ENABLE_DISABLE', "Activar / Desactivar");
Core::define('TEXT_MANAGE_DESCENDANTS', "Administrar solo descendientes directos");
Core::define('TEXT_MANAGE_TREE_DESCENDANTS', "Administrar todos los descendientes");
Core::define('TEXT_MANAGE_TREE_DESCENDANTS_DESC', "Podrá administrar los usuarios creados por él y los de sus hijos.");
Core::define('TEXT_MANAGE_DESCENDANTS_DESC', "Únicamente podrá administrar los usuarios creados por él.");
Core::define('TEXT_LOGIN', "Entrar");
Core::define('TEXT_LOGOUT', "Salir");
Core::define('TEXT_USER_PASSWORD_REQUIRED', "Email & Contraseña son requeridos.");
Core::define('TEXT_PASSWORD', "Contraseña");
Core::define('TEXT_REQUIRED', "Campo requerido");
Core::define('TEXT_INVALID_EMAIL', "Email inválido");
Core::define('TEXT_MIN_LENGTH', "Longitud mínima de 7 caractéres");
Core::define('TEXT_FORM_WARNING', "Por favor completa los campos requeridos *");
Core::define('TEXT_FORM_ERROR', "El formulario tiene errores.");
Core::define('TEXT_FORM_FAILED', "El servidor no responde, Intenta más tarde.");
Core::define('TEXT_FORGOTTEN_PASSWORD', "Olvidó la contraseña?");
Core::define('TEXT_INCORRECT_PASSWORD', "La contraseña es incorrecta.");
Core::define('TEXT_ACCOUNT', "Cuenta");
Core::define('TEXT_EDIT_ACCOUNT', "Editar cuenta");
Core::define('TEXT_PROFILE_PICTURE', "Foto de perfil");
Core::define('TEXT_CHANGE_PASSWORD', "Cambiar contraseña");
Core::define('TEXT_NEW_PASSWORD', "Nueva contraseña");
Core::define('TEXT_CURRENT_PASSWORD', "Contraseña actual");
Core::define('TEXT_RESET_PASSWORD', "Restablecer contraseña");
Core::define('TEXT_CREATE_ACCOUNT', "Crear cuenta");
Core::define('TEXT_APP_IN_DEV_MODE', "App corriendo en modo desarrollo");
Core::define('TEXT_USER', "Usuario");
Core::define('TEXT_USERS', "Usuarios");
Core::define('TEXT_SUBSCRIBERS', "Suscriptores");
Core::define('TEXT_CLIENTS', "Clientes");
Core::define('TEXT_SUPPLIERS', "Proveedores");
Core::define('TEXT_PICTURE', "Foto");
Core::define('TEXT_NO_RESULTS', "No hay resultados.");
Core::define('TEXT_PAGE', "Página");
Core::define('TEXT_CREATE', "Crear");
Core::define('TEXT_NEW', "Nuevo");
Core::define('TEXT_EDIT', "Editar");
Core::define('TEXT_SAVE', "Guardar");
Core::define('TEXT_UPDATE', "Actualizar");
Core::define('TEXT_SUBMIT', "Enviar");
Core::define('TEXT_GENDER', "Género");
Core::define('TEXT_MALE', "Hombre");
Core::define('TEXT_FEMALE', "Mujer");
Core::define('TEXT_UPLOAD', "Subir");
Core::define('TEXT_CROP', "Cortar");
Core::define('TEXT_FIRST_NAME', "Nombre");
Core::define('TEXT_LAST_NAME', "Apellidos");
Core::define('TEXT_CONFIRM_PASSWORD', "Confirmar contraseña");
Core::define('TEXT_PASSWORD_NO_MATCH', "La contraseña no coincide.");
Core::define('TEXT_RECOVER_PASSWORD', "Recuperar contraseña");
Core::define('TEXT_ERROR_SENDING_EMAIL', "No se pudo enviar el email.");
Core::define('TEXT_ERROR_CREATING_USER', "No se pudo crear el usuaro, Intente más tarde.");
Core::define('TEXT_ERROR_RESETING_PASSWORD', "No se pudo restablecer la contraseña");
Core::define('TEXT_FORM_ERRORS', "El servidor tiene errores.");
