<?php
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 *	-----------------
 *	Spanish Texts
 *	-----------------
 */

App::text('TO', "A");
App::text('For', "Para");
App::text('From', "De");
App::text('WELCOME', "Bienvenido");
App::text('WELCOME_TO', TEXT_WELCOME . " a");
App::text('CREATED_ON', "Creado el");
App::text('PARENT', "Padre");
App::text('ROLE', "Rol");
App::text('TREE', "Árbol");
App::text('DATA', "Datos");
App::text('DATE', "Fecha");
App::text('TIME', "Hora");
App::text('YEAR', "Año");
App::text('MONTH', "Mes");
App::text('PREVIOUS', "Anterior");
App::text('NEXT', "Siguiente");
App::text('FILTER', "Filtro");
App::text('TO_FILTER', "Filtrar");
App::text('RESET', "Restablecer");
App::text('SEARCH', "Búsqueda");
App::text('TO_SEARCH', "Buscar");
App::text('DESCENDANTS', "Descendencia");
App::text('START_DATE', "Fecha inicio");
App::text('END_DATE', "Fecha fin");
App::text('ENTRANCES', "Entradas");
App::text('DEPARTURES', "Salidas");
App::text('LANGUAGES', "Idiomas");
App::text('NOT_FOUND', "No encontrado");
App::text('FILE', "Archivo");
App::text('SERVICE_UNAVAILABLE', "Servicio no disponible.");
App::text('LOGGED_IN_STRANGER', "Alguien estaba usando su cuenta en este momento.");
App::text('FILTERED_RESULT', "Resultado filtrado.");
App::text('WAS_AN_ERROR', "Ocurrió un error.");
App::text('UNIQUE_NAME', "Elige un nombre único.");
App::text('AUTH_OK', "Autenticación exitosa!");
App::text('AUTH_FAIL', "Email o contraseña son incorrectos");
App::text('AUTH_DISABLED', "Tu cuenta fue desactivada.");
App::text('USER_NOT_EXIST', "El usuario no existe");
App::text('INVALID_REQUEST', "Solicitud inválida");
App::text('CHANGES_SAVED', "Los cambios fueron guardados con éxito.");
App::text('GRANT_ACCESS_REQUIRED', "No tiene permisos suficientes para realizar esta operación.");
App::text('BACK', "Atrás");
App::text('CLOSE', "Cerrar");
App::text('ALL', "Todos");
App::text('NAME', "Nombre");
App::text('EXAMPLE', "Ejemplo");
App::text('TRASH', "Papelera");
App::text('SURE', "¿Está seguro?");
App::text('YES', "Si");
App::text('COMMENT', "Comentario");
App::text('CONTACT_US', "Contacto");
App::text('GO_TO', "Ir a");
App::text('EXPIRED', "Expiró");
App::text('EXPIRATION_DATE', "Fecha de Expiración");
App::text('EXPIRES', "Expira");
App::text('ONE_MOMENT_PLEASE', "Un momento por favor.");
App::text('UNAVAILABLE_ROLE', "Rol no disponible.");
App::text('PAGE_NOT_FOUND', "Página No Encontrada");
App::text('CHOOSE_AN_OPTION', "Elige una opción.");
App::text('LATEST', "Últimos");
App::text('FULL_NAME', "Nombre");
App::text('VIEW', "Ver");
App::text('ACTIVE', "Activo");
App::text('ENABLE_DISABLE', "Activar / Desactivar");
App::text('MANAGE_DESCENDANTS', "Administrar solo descendientes directos");
App::text('MANAGE_TREE_DESCENDANTS', "Administrar todos los descendientes");
App::text('MANAGE_TREE_DESCENDANTS_DESC', "Podrá administrar los usuarios creados por él y los de sus hijos.");
App::text('MANAGE_DESCENDANTS_DESC', "Únicamente podrá administrar los usuarios creados por él.");
App::text('LOGIN', "Entrar");
App::text('LOGOUT', "Salir");
App::text('USER_PASSWORD_REQUIRED', "Email & Contraseña son requeridos.");
App::text('PASSWORD', "Contraseña");
App::text('REQUIRED', "Campo requerido");
App::text('INVALID_EMAIL', "Email inválido");
App::text('MIN_LENGTH', "Longitud mínima de 7 caractéres");
App::text('FORM_WARNING', "Por favor completa los campos requeridos *");
App::text('FORM_ERROR', "El formulario tiene errores.");
App::text('FORM_FAILED', "El servidor no responde, Intenta más tarde.");
App::text('FORGOTTEN_PASSWORD', "Olvidó la contraseña?");
App::text('INCORRECT_PASSWORD', "La contraseña es incorrecta.");
App::text('ACCOUNT', "Cuenta");
App::text('EDIT_ACCOUNT', "Editar cuenta");
App::text('PROFILE_PICTURE', "Foto de perfil");
App::text('CHANGE_PASSWORD', "Cambiar contraseña");
App::text('NEW_PASSWORD', "Nueva contraseña");
App::text('CURRENT_PASSWORD', "Contraseña actual");
App::text('RESET_PASSWORD', "Restablecer contraseña");
App::text('CREATE_ACCOUNT', "Crear cuenta");
App::text('APP_IN_DEV_MODE', "App corriendo en modo desarrollo");
App::text('USER', "Usuario");
App::text('USERS', "Usuarios");
App::text('SUBSCRIBERS', "Suscriptores");
App::text('CLIENTS', "Clientes");
App::text('SUPPLIERS', "Proveedores");
App::text('PICTURE', "Foto");
App::text('NO_RESULTS', "No hay resultados.");
App::text('PAGE', "Página");
App::text('CREATE', "Crear");
App::text('NEW', "Nuevo");
App::text('EDIT', "Editar");
App::text('SAVE', "Guardar");
App::text('UPDATE', "Actualizar");
App::text('SUBMIT', "Enviar");
App::text('GENDER', "Género");
App::text('MALE', "Hombre");
App::text('FEMALE', "Mujer");
App::text('UPLOAD', "Subir");
App::text('CROP', "Cortar");
App::text('CONTENT', "Contenido");
App::text('FIRST_NAME', "Nombre");
App::text('LAST_NAME', "Apellidos");
App::text('CONFIRM_PASSWORD', "Confirmar contraseña");
App::text('PASSWORD_NO_MATCH', "La contraseña no coincide.");
App::text('RECOVER_PASSWORD', "Recuperar contraseña");
App::text('ERROR_SENDING_EMAIL', "No se pudo enviar el email.");
App::text('ERROR_CREATING_USER', "No se pudo crear el usuaro, Intente más tarde.");
App::text('ERROR_RESETING_PASSWORD', "No se pudo restablecer la contraseña");
App::text('FORM_ERRORS', "El servidor tiene errores.");
