<?php
use Roducks\Page\Template;
use App\Sites\Rod\Modules\Finances\Helper\Finances as FinancesHelper;
?>
<div class="container">
	<div class="row box-white">		
		<div class="col-md-6">
			<?php Template::view("title"); ?>
			<form rel="rdks-form" name="foo" method="post" action="/">
				<select name="id_card" 
				rel="rdks-form-select" 
				class="rdks-form-select" 
				data-text="Selecciona una tarjeta" 
				data-callback="cbFinancesCards">
					<?php if($cards->rows()): while($card = $cards->fetch()): ?>
					<option value="<?php echo $card['id_card']; ?>"><?php echo FinancesHelper::getCardTitle($card['title'],$card['card_number']); ?></option>
					<?php endwhile; endif; ?>
				</select>
			</form>
		</div>
	</div>
</div>
