<?php
use Roducks\Page\Template;
use App\Sites\Rod\Modules\Finances\Helper\Finances as FinancesHelper;
?>
<div class="container">
	<?php Template::view("btn-back"); ?>
	<hr />
	<div class="row box-white">		
		<div class="col-md-6">
			<?php Template::view("title"); ?>
			<form id="foovar" name="foovar" method="post" 
			rel="rdks-form" 
			data-notification="true" 
			data-callback-success="<?php echo Template::conditional($submit, 'cbFormSuccess', 'cbFormSimulationSuccess'); ?>" 
			data-callback-loading="cbFormLoading" 
			data-callback-error="cbFormError" 
			data-alert-warning="Porfavor completa los campos requeridos *" 
			data-alert-error="Por favor corrige el error." 
			data-alert-failed="No esta disponible." 
			data-reset="<?php echo Template::conditional($submit, Template::conditional($edit,'false','true'), 'false'); ?>" 
			data-ajax="true" 
			data-json="true" 
			data-focus="true" 
			action="<?php echo FinancesHelper::getJsonUrl($action); ?>">

				<div class="form-group has-feedback">
				  <label class="control-label" for="first_name">Tarjeta<?php echo Template::conditional($submit, ' utilizada'); ?></label>
				  <select name="id_card" class="form-control" rel="rdks-form-select" data-required="true">
				  	<?php while($card = $cards->fetch()): ?>
				  		<option<?php echo Template::selected( ($card['id_card'] == $row['id_card']) ); ?> value="<?php echo $card['id_card']; ?>"><?php echo FinancesHelper::getCardTitle($card['title'],$card['card_number']); ?></option>
				 	<?php endwhile; ?>
				  </select>
				</div>

				<div class="form-group has-feedback">
					<label class="control-label" for="payment_date"><span class="rdks-ui-color-red">*</span> Fecha Compra</label>
					<input type="hidden" id="payment_date" name="payment_date" value="<?php echo $row['payment_date']; ?>" data-text="<?php echo Template::conditional((!empty($row['payment_date'])), $row['payment_date_format'], 'dd/mm/yyyy'); ?>" rel="rdks-datepicker" data-required="true" data-type="datepicker" data-alert-warning="Fill out Date" data-format="dd/mm/yyyy" data-conf='{"lang":"es","speller":1,"remain":true,"year":<?php echo $year; ?>,"month":<?php echo $month; ?>,"day":<?php echo $day; ?>}' class="form-control" />
				</div>

				<?php if($submit): ?>

				<div class="form-group has-feedback">
					<label class="control-label" for="title"><span class="rdks-ui-color-red">*</span> Tienda / Establecimiento</label>
					<input type="text" name="title" class="form-control" 
					data-required="true" 
					data-alert-warning="It's required." 
					value="<?php echo $row['title']; ?>"
					/>
					<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					<span class="help-block">Ejemplo: Walmart</span>
				</div>

				<div class="form-group has-feedback">
				  <label class="control-label" for="description">Descripción de la compra</label>
				  <textarea class="form-control" name="description" data-required="true" data-label="Campo requerido." data-field="words" data-alert="Error"><?php echo $row['description']; ?></textarea>
				  <p class="help-block"></p>
				  <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				</div>

				<?php endif; ?>

				<div class="form-group has-feedback">
				  <label class="control-label" for="first_name">Plazo</label>
					<select name="period" class="form-control" data-required="true" rel="rdks-form-select">
						<?php foreach ($periods as $period): ?>
						<option<?php echo Template::selected( ($row['period'] == $period['value']) ); ?> value="<?php echo $period['value']; ?>"><?php echo $period['text']; ?></option>
						<?php endforeach; ?>
					</select>
				</div>	

				<div class="form-group has-feedback">
					<label class="control-label" for="total"><span class="rdks-ui-color-red">*</span> Total de la compra</label>
					<div class="input-group">
						<div class="input-group-addon">$</div>
						<input type="text" name="total" class="form-control" placeholder="0.00"
						data-required="true" 
						data-alert-warning="It's required." 
						data-alert-error="Price must have 2 decimals." 
						data-greater="0.00|Greater than zero" 
						data-type="price" 
						value="<?php echo $row['total']; ?>"
						/>
					</div>	
					<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					<span class="help-block">Sin caractéres especiales ($,)</span>		

				</div>
				<?php if($submit): ?>
				<button type="submit" name="send" class="btn btn-lg btn-warning"><span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> <?php echo TEXT_SAVE; ?></button>
				<?php else: ?>
				<button type="submit" name="send" class="btn btn-lg btn-info"><span class="glyphicon glyphicon-scale" aria-hidden="true"></span> Check</button>
				<?php endif; ?>
			</form>

		</div>
	</div>
</div>
