<?php 
use Roducks\Page\Template;
use Roducks\Libs\Utils\Date;
use Roducks\Framework\Language;
use Roducks\Libs\Data\Cart;
use App\Sites\Rod\Modules\Finances\helper\Finances as FinancesHelper;

$total1 = 0;
$total2 = 0;
?>
<div class="container-fluid">
	<?php Template::view("btn-back"); ?>
	<?php if(!empty($today)): ?>
	<hr />
	<h2><?php echo $today; ?></h2>
	<?php endif; ?>
	<hr />
	<div class="left">
		<h1><?php echo $title; ?> - <span class="rdks-ui-color-red">$ <span id="total"></span> MXN</span></h1>
	</div>
	<div class="clear"></div>

	<div class="box-white">

		<table id="data-grid" width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover" data-url-visibility="<?php echo FinancesHelper::getVisibilityUrl(); ?>">
			<tr>
				<th>Pago</th>
				<th>Día Pago</th>
				<th>Cantidad</th>
				<th class="3%">Pagado</th>
				<th class="3%">Activo</th>
				<th class="3%">&nbsp;</th>
			</tr>
			<tr>
				<td colspan="6" style="background: #999; color: #fff; font-weight: bold;">
					FIJOS
				</td>
			</tr>
			<?php if($dataMain->rows()): while($row = $dataMain->fetch()): $total1+= $row['amount']; ?>
			<tr class="<?php echo (($row['day'] - 2) == $day) ? 'selected' : Template::equals($day, $row['day'],'selected'); ?>">
				<td>
					<h3><?php echo $row['title']; ?></h3>
					<?php if(($row['day'] - 2) == $day): ?>
					<button type="button" class="btn btn-warning">Próximo a vencer</button>
					<?php endif; ?>

					<?php if($row['day'] == $day): ?>
					<button type="button" class="btn btn-danger">Hoy vence</button>
					<?php endif; ?>

				</td>
				<td align="center"><?php echo $row['day']; ?></td>
				<td align="right" class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($row['amount'], "MXN"); ?></td>
				<td align="center">

					<button type="button" class="btn btn-<?php echo Template::equals($row['month'],$month, 'success', 'default'); ?>" 
						<?php echo Template::equals($row['month'],$month, 'data-rel', 'rel'); ?>="rdks-action-post" 
						data-url="<?php echo FinancesHelper::getPaidUrl(); ?>" 
						data-params='{"id":<?php echo $row['id_payment']; ?>, "month": <?php echo $month; ?>}' 
						data-callback="cbFinancesPaid" 
						><span class="glyphicon glyphicon-<?php echo Template::equals($row['month'],$month, 'ok', 'exclamation-sign'); ?>" aria-hidden="true"></span>
					</button>

				</td>
				<td align="center">

					<button type="button" class="btn rdks-ui-btn-<?php echo Template::equals($row['active'], 1,"enabled","disabled"); ?>" 
					rel="rdks-popOver"
					data-title="<?php echo TEXT_SURE; ?>" 
					data-callback="cbFinancesVisibility" 
					data-callback-visibility="cbFinancesVisibilityDone" 
					data-buttons='["No","<?php echo TEXT_YES; ?>"]'  
					data-id="<?php echo $row['id_payment']; ?>" 
					data-value="<?php echo $row['active']; ?>" 
					data-params='{"type": "recurrent"}' 
					><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></button>

				</td>
				<td align="center"><a href="<?php echo FinancesHelper::getEditUrl($row['id_payment']); ?>" class="btn btn-info"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
			</tr>
			<?php endwhile; ?>
			<tr class="highlight">
				<td colspan="2" align="right"><h3>Subtotal:</h3></td>
				<td align="right" class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($total1,"MXN"); ?></td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<?php else: ?>
			<tr>
				<td colspan="6">
					<div class="alert alert-warning" role="alert" style="margin:0;">
						<span class="alert-text">
							<span class="glyphicon glyphicon-alert" aria-hidden="true"></span> <?php echo TEXT_NO_RESULTS; ?>
						</span>
					</div>
				</td>
			</tr>
			<?php endif; ?>	
			<tr>
				<td colspan="6" style="background: #999; color: #fff; font-weight: bold;">
					VARIABLES
				</td>
			</tr>
			<?php if($dataSecundary->rows()): while($row = $dataSecundary->fetch()): $total2+= $row['amount']; ?>
			<tr class="<?php echo (($row['day'] - 2) == $day) ? 'selected' : Template::equals($day, $row['day'],'selected'); ?>">
				<td>
					<h3><?php echo $row['title']; ?></h3>
					<?php if(($row['day'] - 2) == $day): ?>
					<button type="button" class="btn btn-warning">Próximo a vencer</button>
					<?php endif; ?>

					<?php if($row['day'] == $day): ?>
					<button type="button" class="btn btn-danger">Hoy vence</button>
					<?php endif; ?>

				</td>
				<td align="center"><?php echo $row['day']; ?></td>
				<td align="right" class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($row['amount'], "MXN"); ?></td>
				<td align="center">

					<button type="button" class="btn btn-<?php echo Template::equals($row['month'],$month, 'success', 'default'); ?>" 
						<?php echo Template::equals($row['month'],$month, 'data-rel', 'rel'); ?>="rdks-action-post" 
						data-url="<?php echo FinancesHelper::getPaidUrl(); ?>" 
						data-params='{"id":<?php echo $row['id_payment']; ?>, "month": <?php echo $month; ?>}' 
						data-callback="cbFinancesPaid" 
						><span class="glyphicon glyphicon-<?php echo Template::equals($row['month'],$month, 'ok', 'exclamation-sign'); ?>" aria-hidden="true"></span>
					</button>

				</td>
				<td align="center">

					<button type="button" class="btn rdks-ui-btn-<?php echo Template::equals($row['active'], 1,"enabled","disabled"); ?>" 
					rel="rdks-popOver"
					data-title="<?php echo TEXT_SURE; ?>" 
					data-callback="cbFinancesVisibility" 
					data-callback-visibility="cbFinancesVisibilityDone" 
					data-buttons='["No","<?php echo TEXT_YES; ?>"]'  
					data-id="<?php echo $row['id_payment']; ?>" 
					data-value="<?php echo $row['active']; ?>" 
					data-params='{"type": "recurrent"}' 
					><span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span></button>

				</td>
				<td align="center"><a href="<?php echo FinancesHelper::getEditUrl($row['id_payment']); ?>" class="btn btn-info"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a></td>
			</tr>
			<?php endwhile; else: ?>
			<tr>
				<td colspan="6">
					<div class="alert alert-warning" role="alert" style="margin:0;">
						<span class="alert-text">
							<span class="glyphicon glyphicon-alert" aria-hidden="true"></span> <?php echo TEXT_NO_RESULTS; ?>
						</span>
					</div>
				</td>
			</tr>
			<?php endif; ?>
			<tr>
			<?php foreach($dataPlus as $card): $total2+= $card['total']; ?>
				<td><h3><?php echo $card['title']; ?></h3></td>
				<td align="center"><?php echo $card['day']; ?></td>
				<td align="right" class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($card['total'],"MXN"); ?></td>
				<td align="center">
					<?php if($day > 27): ?>
					<button type="button" class="btn btn-<?php echo Template::equals($card['month'],$month, 'success', 'default'); ?>" 
						<?php echo Template::equals($card['month'],$month, 'data-rel', 'rel'); ?>="rdks-action-post" 
						data-url="<?php echo FinancesHelper::getPaidCardUrl(); ?>" 
						data-params='{"id":<?php echo $card['id_card']; ?>, "month": <?php echo $month; ?>}' 
						data-callback="cbFinancesPaid" 
						><span class="glyphicon glyphicon-<?php echo Template::equals($card['month'],$month, 'ok', 'exclamation-sign'); ?>" aria-hidden="true"></span>
					</button>
					<?php endif; ?>
				</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			<?php endforeach; ?>
			</tr>
			<tr class="highlight">
				<td colspan="2" align="right"><h3>Subtotal:</h3></td>
				<td align="right" class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($total2,"MXN"); ?></td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
		</table>

		<input type="hidden" id="sum" name="sum" value="<?php echo ($total1 + $total2); ?>" />
	</div>
</div>