domain.name: '*'
timezone: America/New_York
site.title: Roducks
email:
    to: contact@yoursite.com
    from: noreply@yoursite.com
logo.image: roducks_logo.png
find.url.in.db: false
subscribers:
    allow.register: true
    expire: false
    how.long: 2    
    period: MONTHS
language:
    default: en
    multilanguage: true
    user.browser: true
content.type: 'text/html; charset=utf-8'
viewport: 'width=device-width,initial-scale=1,shrink-to-fit=no'
