<?php
use rdks\core\framework\Language;
use rdks\core\libs\Utils\Date;
use rdks\core\page\Template;
?>
<div class="container-fluid">
   <div class="box-white">
   		<?php 
   			Template::view("reset-filters"); 
   			Template::view("datepicker-range"); 
   		?>
		<table id="data-grid" width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover">
			<tr>
				<th align="left"><?php echo TEXT_DATE; ?></th>
				<th width="5%">&nbsp;</th>				
			</tr>	
		<?php if(count($data) > 0): foreach($data as $row): ?>
			<tr>
				<td><span class="glyphicon glyphicon-calendar" aria-hidden="true"></span> <?php echo Date::getDateFormat($row['log_date'], Language::get()); ?></td>
				<td><button type="button" onclick="userLogs(<?php echo $id_user; ?>,'<?php echo $row['log_date']; ?>');" class="btn btn-primary"><span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> <?php echo TEXT_ENTRANCES;?> / <?php echo TEXT_DEPARTURES;?></button></td>
			</tr>
		<?php endforeach; else: ?>
			<tr>
				<td colspan="2">
					<div class="alert alert-warning" role="alert" style="margin:0;">
						<span class="alert-text">
							<span class="glyphicon glyphicon-alert" aria-hidden="true"></span> <?php echo TEXT_NO_RESULTS; ?>
						</span>
					</div>
				</td>
			</tr>
		<?php endif; ?>	
		</table>
	</div>
</div>