<div class="container">
	<div class="box-white">
		<div class="row">
			<div class="col-md-6">

				<form id="foovar" name="foovar" method="post" 
				rel="rdks-form" 
				data-notification="true" 
				data-callback-success="cbFormSuccess" 
				data-callback-loading="cbFormLoading" 
				data-callback-error="cbFormError" 
			    data-alert-warning="<?php echo TEXT_FORM_WARNING; ?>" 
			    data-alert-error="<?php echo TEXT_FORM_ERROR; ?>" 
			    data-alert-failed="<?php echo TEXT_FORM_FAILED; ?>" 
				data-ajax="true" 
				data-json="true" 
				data-focus="true" 
				action="/_json/users/change-password">

				<div class="form-group has-feedback">
				  <label class="control-label" for="password"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_CURRENT_PASSWORD; ?></label>
					<input type="password" class="form-control" name="password"
					rel="rdks-form-input-post" 
					data-url="/_service/auth/paywall-admin" 
					data-required="true" 
					data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
					data-type="password" 
					/>
				  <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
				  <span class="help-block"></span>
				</div>

				<div class="form-group has-feedback">
					<label class="control-label" for="new_password"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_NEW_PASSWORD; ?></label>
					<input type="password" name="new_password" class="form-control" 
					data-required="true" 
					data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
					data-minlength="7|<?php echo TEXT_MIN_LENGTH; ?>" 
					data-type="password" 
					data-strength="true"
					/>

					<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					<span class="help-block"></span>
				</div>

				<div class="form-group has-feedback">
					<label class="control-label" for="confirm_password"><span class="rdks-ui-color-red">*</span> <?php echo TEXT_CONFIRM_PASSWORD; ?></label>
					<input type="password" name="confirm_password" class="form-control" 
					data-match="input[name='new_password']|<?php echo TEXT_PASSWORD_NO_MATCH; ?>" 
					data-alert-warning="<?php echo TEXT_REQUIRED; ?>" 
					data-required="true" 
					data-type="password"
					/>
					<span class="glyphicon form-control-feedback" aria-hidden="true"></span>
					<span class="help-block"></span>
				</div>

				<button type="submit" class="btn btn-lg btn-warning navbar-btn">
					<span class="glyphicon glyphicon-floppy-disk" aria-hidden="true"></span> <?php echo TEXT_SAVE; ?>
				</button>
				
			</form>

			</div>
		</div>		
	</div>
</div>