<?php 
use Roducks\Framework\URL;
?>
<ul class="dropdown-menu">
	<li><a href="<?php echo URL::getAdminURL(); ?>"><span class="glyphicon glyphicon-stats" aria-hidden="true"></span> Dashboard</a></li>                   
	<li role="separator" class="divider"></li>
	<li><a href="/contact-us"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span> <?php echo TEXT_CONTACT_US; ?></a></li>     
</ul>