<!DOCTYPE html>
<html>
<head>
	<?php echo $_META; ?>
    <title><?php echo $_TITLE; ?></title>
    <?php echo $_FAVICON; ?>
    <?php echo $_CSS; ?>
    <?php echo $_JS; ?>
<style type="text/css">

body{
	background: #F5F5F5;
	font-family: Arial;
	padding: 0;
	margin: 0;
}

.page-not-found{
	display: none;
	width: 600px;
	background: #FFF;
	padding: 40px;
	text-align: center;
  	box-shadow: 0 0 2px 1px #999;
}

</style>
	<?php echo $_JS; ?>
</head>
<body>
