<?php
use Roducks\Framework\Environment;
use Roducks\Page\Block;
use Roducks\Page\Template;
?>
<div id="top" style="height:50px;"></div>
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
<div class="container">
 
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/" style="position:relative; top:-4px;">Rod</a>
    </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
            <li class="active"><a href="/"><span class="glyphicon glyphicon-home" aria-hidden="true"></span><span class="sr-only">(current)</span></a></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Menu <span class="caret"></span></a>
                <?php Block::load("menu/simple", ['items' => Template::menu("top-finances"), 'tpl' => "top"]); ?>
            </li>
        </ul>
 
        <?php Block::load("language/output/{$_URL_ID}/nav"); ?>
     
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
             
            </li>
        </ul> 
 
    </div><!-- /.navbar-collapse -->
</div><!-- /.container-fluid -->
</nav>
 
<?php if(Environment::inDEV()): ?>
<div class="alert alert-warning" role="alert">
    <span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
    <span class="alert-text"><?php echo TEXT_APP_IN_DEV_MODE; ?></span>
</div>
<?php endif; ?> 