<?php use Roducks\Libs\Data\Cart; ?>
<hr />
<b>Fecha de Compra:</b> <?php echo $payment_date; ?>
<br>
<b>Total: <span class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($total, "MXN"); ?></span></b>
<br>
<?php if($period > 1): ?>
<b><?php echo $period; ?> Pagos de: <span class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($amount, "MXN"); ?></span></b>
<?php endif; ?>
<hr />
<h4>Total a pagar en <?php echo $monthLabel; ?>:</h4>
<h3 class="rdks-ui-color-red"><?php echo Cart::getPriceFormat($totals, "MXN"); ?></h3>