<?php 
use rdks\core\page\Template;
use rdks\app\sites\blog\modules\Posts\helper\Posts as PostsHelper; 
?>
<div class="container-fluid">
    
    <?php if($latestTag): ?>
        <div class="well"><h1>Posts (<?php echo $totalRows; ?>)</h1></div>
        <h1>Latest: <a href="#" id="latest-post"></a></h1>
    <?php else: ?>
        <div class="well"><h1><?php echo $categoryTitle; ?> (<?php echo $totalRows; ?>)</h1></div>
        <?php Template::view("btn-back"); ?>
    <?php endif; ?>
 
    <?php if($data->rows()): ?>
    <div><b>Page: </b><span id="pageControl-pager">1 / 1</span></div>
 
    <nav class="text-centered">
        <ul id="pageControl-ctrls-back" class="pagination"></ul>        
        <ul id="pageControl" class="pagination"></ul>
        <ul id="pageControl-search" class="pagination"></ul>
        <ul id="pageControl-ctrls-next" class="pagination"></ul>
    </nav>
    <?php endif; ?>
 
    <div class="box-white">
 
    <?php if($data->rows()): while($post = $data->fetch()): ?>
        <h1><a href="<?php echo PostsHelper::getPostLink($post['postId']); ?>"><?php echo $post['title']; ?></a></h1>
        <span>By: <?php echo $post['author']; ?></span> | <span><a href="<?php echo PostsHelper::getCategoryLink($post['id_category']); ?>"><?php echo $post['category']; ?></a></span>
 
    <?php endwhile; else: ?>
        <h4>There are no posts to be shown.</h4>
    <?php endif; ?>   
 
    </div>
 
</div>