<?php
use rdks\core\framework\UI;
use rdks\core\framework\URL;
use rdks\core\framework\Language;
?>
<?php echo UI::getLogo(300, [
	'http' => URL::getPublicURL(),
	'flex-h' => true, // width: 300px, height: auto
	'center' => true, 
	'bg' => UI::BG_TRANSPARENT, // UI::BG_WHITE | UI::BG_BLACK
]); ?>
<br>
<h1><?php echo TEXT_RESET_PASSWORD; ?></h1>

<b><?php echo Language::translate("Copy this URL below and paste in your Browser","Copia esta URL y pégala en tu Navegador"); ?>:</b>
<div style="background: #eee; padding: 10px;">
	<?php echo URL::getPublicURL("/account/reset-password/token/{$data['token']}"); ?>
</div>