<?php 
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

$plugins = [
	'bootstrap' => [
		'bootstrap-3.3.5/css/bootstrap.min.css',
		'bootstrap-3.3.5/js/bootstrap.min.js'
	], 
	'jquery-jcrop' => [
		'jquery-jcrop-0.9.12/css/jquery.jcrop.css',
		'jquery-jcrop-0.9.12/js/jquery.jcrop.min.js'
	],
	'roducks' => [
		'roducks-1.0/css/roducks.css',
		'roducks-1.0/css/themes/default/roducks-modal.css',
		'roducks-1.0/js/roducks.min.js'
	]
];

