<?php 
/**
 *
 * This file is part of Roducks.
 *
 *    Roducks is free software: you can redistribute it and/or modify
 *    it under the terms of the GNU General Public License as published by
 *    the Free Software Foundation, either version 3 of the License, or
 *    (at your option) any later version.
 *
 *    Roducks is distributed in the hope that it will be useful,
 *    but WITHOUT ANY WARRANTY; without even the implied warranty of
 *    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *    GNU General Public License for more details.
 *
 *    You should have received a copy of the GNU General Public License
 *    along with Roducks.  If not, see <http://www.gnu.org/licenses/>.
 *
 */

return [
	'bootstrap' => [
		'bootstrap-3.3.5/css/bootstrap.min.css?v=1.0',
		'bootstrap-3.3.5/js/bootstrap.min.js?v=1.0'
	], 
	'jquery-jcrop' => [
		'jquery-jcrop-0.9.12/css/jquery.jcrop.css?v=1.0',
		'jquery-jcrop-0.9.12/js/jquery.jcrop.min.js?v=1.0'
	],
	'roducks' => [
		'roducks-1.0/css/roducks.css?v=1.7',
		'roducks-1.0/css/themes/default/roducks-modal.css?v=1.0',
		'roducks-1.0/js/roducks.min.js?v=1.7'
		//'roducks-1.0/js/roducks-1.0.js?v=1.5'		
	],
	'roducks-cart' => [
		'css/roducks.cart.css?v=1.0',
		'js/roducks.cart.js?v=1.0',
		'js/roducks.steps.js?v=1.0'
	],
	'roducks-checkout' => [
		'css/roducks.checkout.css?v=1.0',
		'js/roducks.checkout.js?v=1.0'
	]
];

