<div class="row">
	<div class="col-md-6">
		<table width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover">
			<tr>
				<th><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> IP</th>
				<th><span class="glyphicon glyphicon-time" aria-hidden="true"></span> <?php echo TEXT_ENTRANCES; ?></th>
			</tr>		
		<?php foreach($data->logIn as $row): ?>
			<tr>
				<td align="center"><?php echo $row->ip->__toString(); ?></td>
				<td align="right"><?php echo $row->time->__toString(); ?></td>
		<?php endforeach; ?>
		</table>
	</div>	
	<div class="col-md-6">
		<table width="100%" cellpadding="0" cellspacing="0" class="rdks-table rdks-table-hover">
			<tr>
				<th><span class="glyphicon glyphicon-time" aria-hidden="true"></span> <?php echo TEXT_DEPARTURES; ?></th>
				<th><span class="glyphicon glyphicon-map-marker" aria-hidden="true"></span> IP</th>
			</tr>		
		<?php foreach($data->logOut as $row): ?>
				<td><?php echo $row->time->__toString(); ?></td>
				<td align="center"><?php echo $row->ip->__toString(); ?></td>
			</tr>
		<?php endforeach; ?>
		</table>
	</div>
</div>
