<?php 
use Roducks\Framework\Login;

$i=0; foreach ($items as $key => $value): 

	if(is_array($value['access']) && count($value['access']) == 2) {
		$action = isset($access[$value['access'][0]][$value['access'][1]]);
		$all = "refuse";
	} else {
		$action = isset($access[ $value['access'] ]);
		$all = $value['access'];
	}

	if($action || $all == "all" || Login::isSuperAdmin()): $i++; 

?>	
<ul class="nav nav-sidebar">
	<li class="active"><a href="<?php echo $value['link']; ?>"><?php echo $value['text']; ?> <span class="sr-only">(current)</span></a></li>
</ul>
 
<ul class="nav nav-sidebar">
	<?php foreach ($value['children'] as $k => $v):  

	if(is_array($v['access']) && count($v['access']) == 2) {
		$ac = isset($access[$v['access'][0]][$v['access'][1]]);
		$al = "refuse";
	} else {
		$ac = isset($access[ $v['access'] ]);
		$al = $value['access'];
	}

	if($ac || $al == "all" || Login::isSuperAdmin()):

	?>
		<li><a href="<?php echo $v['link']; ?>"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> <?php echo $v['text']; ?></a></li>
	<?php endif; endforeach; ?>
</ul>
<?php endif; ?>
<?php endforeach; ?>
<?php if($i > 0): ?>
<hr />
<?php endif; ?>