<?php
use Roducks\Data\User;
?>
<ul class="dropdown-menu">
<?php foreach ($items as $key => $value) : ?>
	<?php if (isset($value['separator'])) : ?>
	<li role="separator" class="divider"></li>
<?php else:

	if (!isset($value['access'])) {
		$value['access'] = "all";
	}

	if (is_array($value['access']) && count($value['access']) == 2) {
		$action = isset($access[$value['access'][0]][$value['access'][1]]);
		$all = "refuse";
	} else {
		$action = isset($access[ $value['access'] ]);
		$all = $value['access'];
	}

	if ($action || $all == "all" || User::isSuperAdmin()) :

?>
		<li>
			<a href="<?php echo $value['link']; ?>">
		<?php if (isset($value['icon'])): ?>
			<span class="glyphicon glyphicon-<?php echo $value['icon']; ?>" aria-hidden="true"></span>
		<?php endif; ?>
			<?php echo $value['text']; ?></a>
		</li>
	<?php endif; ?>
<?php endif; ?>
<?php endforeach; ?>
</ul>
